// Generated from api_manifest.json. Do not edit directly.
#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <Python.h>
#include <algorithm>
#include <array>
#include <cerrno>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <dlfcn.h>
#include <mutex>
#include <stdexcept>
#include <string>
#include <vector>
#include <unistd.h>
extern "C" {
#include "wiringPi/wiringPi.h"
}

namespace nb = nanobind;


static PyObject *g_isr_callbacks[MAX_PIN_NUM] = {nullptr};
static std::mutex g_isr_mutex;
template <size_t I> static void isr_trampoline() noexcept {
    nb::gil_scoped_acquire gil;
    PyObject *cb = g_isr_callbacks[I];
    if (!cb) return;
    Py_INCREF(cb);
    PyObject *r = PyObject_CallNoArgs(cb);
    if (!r) PyErr_WriteUnraisable(cb); else Py_DECREF(r);
    Py_DECREF(cb);
}
using IsrFn = void (*)();
static IsrFn isr_fn(size_t i) { switch(i) {
    case 0: return &isr_trampoline<0>;
    case 1: return &isr_trampoline<1>;
    case 2: return &isr_trampoline<2>;
    case 3: return &isr_trampoline<3>;
    case 4: return &isr_trampoline<4>;
    case 5: return &isr_trampoline<5>;
    case 6: return &isr_trampoline<6>;
    case 7: return &isr_trampoline<7>;
    case 8: return &isr_trampoline<8>;
    case 9: return &isr_trampoline<9>;
    case 10: return &isr_trampoline<10>;
    case 11: return &isr_trampoline<11>;
    case 12: return &isr_trampoline<12>;
    case 13: return &isr_trampoline<13>;
    case 14: return &isr_trampoline<14>;
    case 15: return &isr_trampoline<15>;
    case 16: return &isr_trampoline<16>;
    case 17: return &isr_trampoline<17>;
    case 18: return &isr_trampoline<18>;
    case 19: return &isr_trampoline<19>;
    case 20: return &isr_trampoline<20>;
    case 21: return &isr_trampoline<21>;
    case 22: return &isr_trampoline<22>;
    case 23: return &isr_trampoline<23>;
    case 24: return &isr_trampoline<24>;
    case 25: return &isr_trampoline<25>;
    case 26: return &isr_trampoline<26>;
    case 27: return &isr_trampoline<27>;
    case 28: return &isr_trampoline<28>;
    case 29: return &isr_trampoline<29>;
    case 30: return &isr_trampoline<30>;
    case 31: return &isr_trampoline<31>;
    case 32: return &isr_trampoline<32>;
    case 33: return &isr_trampoline<33>;
    case 34: return &isr_trampoline<34>;
    case 35: return &isr_trampoline<35>;
    case 36: return &isr_trampoline<36>;
    case 37: return &isr_trampoline<37>;
    case 38: return &isr_trampoline<38>;
    case 39: return &isr_trampoline<39>;
    case 40: return &isr_trampoline<40>;
    case 41: return &isr_trampoline<41>;
    case 42: return &isr_trampoline<42>;
    case 43: return &isr_trampoline<43>;
    case 44: return &isr_trampoline<44>;
    case 45: return &isr_trampoline<45>;
    case 46: return &isr_trampoline<46>;
    case 47: return &isr_trampoline<47>;
    case 48: return &isr_trampoline<48>;
    case 49: return &isr_trampoline<49>;
    case 50: return &isr_trampoline<50>;
    case 51: return &isr_trampoline<51>;
    case 52: return &isr_trampoline<52>;
    case 53: return &isr_trampoline<53>;
    case 54: return &isr_trampoline<54>;
    case 55: return &isr_trampoline<55>;
    case 56: return &isr_trampoline<56>;
    case 57: return &isr_trampoline<57>;
    case 58: return &isr_trampoline<58>;
    case 59: return &isr_trampoline<59>;
    case 60: return &isr_trampoline<60>;
    case 61: return &isr_trampoline<61>;
    case 62: return &isr_trampoline<62>;
    case 63: return &isr_trampoline<63>;
    default: return nullptr; } }

static PyObject *g_thread_callbacks[16] = {nullptr};
static std::mutex g_thread_mutex;
template <size_t I> static void *thread_trampoline(void *) noexcept {
    nb::gil_scoped_acquire gil;
    PyObject *cb = nullptr;
    { std::lock_guard<std::mutex> lock(g_thread_mutex); cb = g_thread_callbacks[I]; g_thread_callbacks[I] = nullptr; }
    if (!cb) return nullptr;
    PyObject *r = PyObject_CallNoArgs(cb);
    if (!r) PyErr_WriteUnraisable(cb); else Py_DECREF(r);
    Py_DECREF(cb);
    return nullptr;
}
using ThreadFn = void *(*)(void *);
static ThreadFn thread_fn(size_t i) { switch(i) {
    case 0: return &thread_trampoline<0>;
    case 1: return &thread_trampoline<1>;
    case 2: return &thread_trampoline<2>;
    case 3: return &thread_trampoline<3>;
    case 4: return &thread_trampoline<4>;
    case 5: return &thread_trampoline<5>;
    case 6: return &thread_trampoline<6>;
    case 7: return &thread_trampoline<7>;
    case 8: return &thread_trampoline<8>;
    case 9: return &thread_trampoline<9>;
    case 10: return &thread_trampoline<10>;
    case 11: return &thread_trampoline<11>;
    case 12: return &thread_trampoline<12>;
    case 13: return &thread_trampoline<13>;
    case 14: return &thread_trampoline<14>;
    case 15: return &thread_trampoline<15>;
    default: return nullptr; } }
NB_MODULE(wiring_pi, m) {
  m.doc() = "nanobind bindings for wiringPi/wiringPi.h";
  auto cls_SunxiGPIOInfo = nb::class_<sunxi_gpio_info>(m, "SunxiGPIOInfo").def(nb::init<>());
  cls_SunxiGPIOInfo.def_rw("gpio_base_addr", &sunxi_gpio_info::gpio_base_addr);
  cls_SunxiGPIOInfo.def_rw("r_gpio_base_addr", &sunxi_gpio_info::r_gpio_base_addr);
  cls_SunxiGPIOInfo.def_prop_rw("gpio_address", [](sunxi_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio); }, [](sunxi_gpio_info &self, uintptr_t value) { self.gpio = reinterpret_cast<decltype(self.gpio)>(value); });
  cls_SunxiGPIOInfo.def_prop_rw("r_gpio_address", [](sunxi_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.r_gpio); }, [](sunxi_gpio_info &self, uintptr_t value) { self.r_gpio = reinterpret_cast<decltype(self.r_gpio)>(value); });
  cls_SunxiGPIOInfo.def_rw("gpio_base_offset", &sunxi_gpio_info::gpio_base_offset);
  cls_SunxiGPIOInfo.def_rw("r_gpio_base_offset", &sunxi_gpio_info::r_gpio_base_offset);
  cls_SunxiGPIOInfo.def_rw("gpio_bank_offset", &sunxi_gpio_info::gpio_bank_offset);
  cls_SunxiGPIOInfo.def_rw("pull_offset", &sunxi_gpio_info::pull_offset);
  cls_SunxiGPIOInfo.def_rw("r_gpio_pull_offset", &sunxi_gpio_info::r_gpio_pull_offset);
  cls_SunxiGPIOInfo.def_rw("gpio_cfg_mask", &sunxi_gpio_info::gpio_cfg_mask);
  cls_SunxiGPIOInfo.def_rw("pwm_base_addr", &sunxi_gpio_info::pwm_base_addr);
  cls_SunxiGPIOInfo.def_prop_rw("pwm_address", [](sunxi_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm); }, [](sunxi_gpio_info &self, uintptr_t value) { self.pwm = reinterpret_cast<decltype(self.pwm)>(value); });
  cls_SunxiGPIOInfo.def_rw("pwm_ctrl", &sunxi_gpio_info::pwm_ctrl);
  cls_SunxiGPIOInfo.def_rw("pwm_period", &sunxi_gpio_info::pwm_period);
  cls_SunxiGPIOInfo.def_rw("pwm_clk", &sunxi_gpio_info::pwm_clk);
  cls_SunxiGPIOInfo.def_rw("pwm_en", &sunxi_gpio_info::pwm_en);
  cls_SunxiGPIOInfo.def_rw("pwm_type", &sunxi_gpio_info::pwm_type);
  cls_SunxiGPIOInfo.def_rw("pwm_bit_en", &sunxi_gpio_info::pwm_bit_en);
  cls_SunxiGPIOInfo.def_rw("pwm_bit_act", &sunxi_gpio_info::pwm_bit_act);
  cls_SunxiGPIOInfo.def_rw("pwm_bit_sclk", &sunxi_gpio_info::pwm_bit_sclk);
  cls_SunxiGPIOInfo.def_rw("pwm_bit_mode", &sunxi_gpio_info::pwm_bit_mode);
  cls_SunxiGPIOInfo.def_rw("pwm_bit_pulse", &sunxi_gpio_info::pwm_bit_pulse);
  auto cls_Rk3588SocInfo = nb::class_<rk3588_soc_info>(m, "Rk3588SocInfo").def(nb::init<>());
  cls_Rk3588SocInfo.def_prop_rw("gpio0_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio0_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.gpio0_base = reinterpret_cast<decltype(self.gpio0_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("gpio1_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio1_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.gpio1_base = reinterpret_cast<decltype(self.gpio1_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("gpio2_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio2_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.gpio2_base = reinterpret_cast<decltype(self.gpio2_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("gpio3_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio3_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.gpio3_base = reinterpret_cast<decltype(self.gpio3_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("gpio4_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio4_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.gpio4_base = reinterpret_cast<decltype(self.gpio4_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("pmu1_ioc_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pmu1_ioc_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.pmu1_ioc_base = reinterpret_cast<decltype(self.pmu1_ioc_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("pmu2_ioc_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pmu2_ioc_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.pmu2_ioc_base = reinterpret_cast<decltype(self.pmu2_ioc_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("bus_ioc_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.bus_ioc_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.bus_ioc_base = reinterpret_cast<decltype(self.bus_ioc_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("cur_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.cur_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.cur_base = reinterpret_cast<decltype(self.cur_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("pmu1cur_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pmu1cur_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.pmu1cur_base = reinterpret_cast<decltype(self.pmu1cur_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("vccio1_4_ioc_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.vccio1_4_ioc_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.vccio1_4_ioc_base = reinterpret_cast<decltype(self.vccio1_4_ioc_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("vccio3_5_ioc_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.vccio3_5_ioc_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.vccio3_5_ioc_base = reinterpret_cast<decltype(self.vccio3_5_ioc_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("vccio6_ioc_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.vccio6_ioc_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.vccio6_ioc_base = reinterpret_cast<decltype(self.vccio6_ioc_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("pwm0_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm0_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.pwm0_base = reinterpret_cast<decltype(self.pwm0_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("pwm1_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm1_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.pwm1_base = reinterpret_cast<decltype(self.pwm1_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("pwm2_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm2_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.pwm2_base = reinterpret_cast<decltype(self.pwm2_base)>(value); });
  cls_Rk3588SocInfo.def_prop_rw("pwm3_base_address", [](rk3588_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm3_base); }, [](rk3588_soc_info &self, uintptr_t value) { self.pwm3_base = reinterpret_cast<decltype(self.pwm3_base)>(value); });
  cls_Rk3588SocInfo.def_rw("pwm_base", &rk3588_soc_info::pwm_base);
  cls_Rk3588SocInfo.def_rw("pwm_mux", &rk3588_soc_info::pwm_mux);
  cls_Rk3588SocInfo.def_rw("pwm_mux_val", &rk3588_soc_info::pwm_mux_val);
  cls_Rk3588SocInfo.def_rw("pwm_mux_offset", &rk3588_soc_info::pwm_mux_offset);
  cls_Rk3588SocInfo.def_rw("ch_period_hpr", &rk3588_soc_info::ch_period_hpr);
  cls_Rk3588SocInfo.def_rw("ch_duty_lpr", &rk3588_soc_info::ch_duty_lpr);
  cls_Rk3588SocInfo.def_rw("ch_crtl", &rk3588_soc_info::ch_crtl);
  auto cls_Rk3566SocInfo = nb::class_<rk3566_soc_info>(m, "Rk3566SocInfo").def(nb::init<>());
  cls_Rk3566SocInfo.def_prop_rw("gpio0_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio0_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.gpio0_base = reinterpret_cast<decltype(self.gpio0_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("gpio1_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio1_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.gpio1_base = reinterpret_cast<decltype(self.gpio1_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("gpio2_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio2_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.gpio2_base = reinterpret_cast<decltype(self.gpio2_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("gpio3_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio3_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.gpio3_base = reinterpret_cast<decltype(self.gpio3_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("gpio4_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio4_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.gpio4_base = reinterpret_cast<decltype(self.gpio4_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("pmu_grf_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pmu_grf_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.pmu_grf_base = reinterpret_cast<decltype(self.pmu_grf_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("sys_grf_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.sys_grf_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.sys_grf_base = reinterpret_cast<decltype(self.sys_grf_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("cru_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.cru_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.cru_base = reinterpret_cast<decltype(self.cru_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("pmu_cru_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pmu_cru_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.pmu_cru_base = reinterpret_cast<decltype(self.pmu_cru_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("pwm2_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm2_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.pwm2_base = reinterpret_cast<decltype(self.pwm2_base)>(value); });
  cls_Rk3566SocInfo.def_prop_rw("pwm3_base_address", [](rk3566_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm3_base); }, [](rk3566_soc_info &self, uintptr_t value) { self.pwm3_base = reinterpret_cast<decltype(self.pwm3_base)>(value); });
  cls_Rk3566SocInfo.def_rw("cru_gate_con", &rk3566_soc_info::cru_gate_con);
  cls_Rk3566SocInfo.def_rw("cru_gate_con_offset", &rk3566_soc_info::cru_gate_con_offset);
  cls_Rk3566SocInfo.def_rw("pwm_base", &rk3566_soc_info::pwm_base);
  cls_Rk3566SocInfo.def_rw("pwm_mux", &rk3566_soc_info::pwm_mux);
  cls_Rk3566SocInfo.def_rw("pwm_mux_val", &rk3566_soc_info::pwm_mux_val);
  cls_Rk3566SocInfo.def_rw("pwm_mux_offset", &rk3566_soc_info::pwm_mux_offset);
  cls_Rk3566SocInfo.def_rw("ch_period_hpr", &rk3566_soc_info::ch_period_hpr);
  cls_Rk3566SocInfo.def_rw("ch_duty_lpr", &rk3566_soc_info::ch_duty_lpr);
  cls_Rk3566SocInfo.def_rw("ch_crtl", &rk3566_soc_info::ch_crtl);
  auto cls_Rk3399SocInfo = nb::class_<rk3399_soc_info>(m, "Rk3399SocInfo").def(nb::init<>());
  cls_Rk3399SocInfo.def_prop_rw("gpio2_base_address", [](rk3399_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio2_base); }, [](rk3399_soc_info &self, uintptr_t value) { self.gpio2_base = reinterpret_cast<decltype(self.gpio2_base)>(value); });
  cls_Rk3399SocInfo.def_prop_rw("grf_base_address", [](rk3399_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.grf_base); }, [](rk3399_soc_info &self, uintptr_t value) { self.grf_base = reinterpret_cast<decltype(self.grf_base)>(value); });
  cls_Rk3399SocInfo.def_prop_rw("cru_base_address", [](rk3399_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.cru_base); }, [](rk3399_soc_info &self, uintptr_t value) { self.cru_base = reinterpret_cast<decltype(self.cru_base)>(value); });
  cls_Rk3399SocInfo.def_prop_rw("pmucru_base_address", [](rk3399_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pmucru_base); }, [](rk3399_soc_info &self, uintptr_t value) { self.pmucru_base = reinterpret_cast<decltype(self.pmucru_base)>(value); });
  cls_Rk3399SocInfo.def_prop_rw("pmugrf_base_address", [](rk3399_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pmugrf_base); }, [](rk3399_soc_info &self, uintptr_t value) { self.pmugrf_base = reinterpret_cast<decltype(self.pmugrf_base)>(value); });
  cls_Rk3399SocInfo.def_prop_rw("gpio1_base_address", [](rk3399_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio1_base); }, [](rk3399_soc_info &self, uintptr_t value) { self.gpio1_base = reinterpret_cast<decltype(self.gpio1_base)>(value); });
  cls_Rk3399SocInfo.def_prop_rw("gpio4_base_address", [](rk3399_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio4_base); }, [](rk3399_soc_info &self, uintptr_t value) { self.gpio4_base = reinterpret_cast<decltype(self.gpio4_base)>(value); });
  auto cls_Rk3328SocInfo = nb::class_<rk3328_soc_info>(m, "Rk3328SocInfo").def(nb::init<>());
  cls_Rk3328SocInfo.def_prop_rw("gpio2_base_address", [](rk3328_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio2_base); }, [](rk3328_soc_info &self, uintptr_t value) { self.gpio2_base = reinterpret_cast<decltype(self.gpio2_base)>(value); });
  cls_Rk3328SocInfo.def_prop_rw("gpio3_base_address", [](rk3328_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio3_base); }, [](rk3328_soc_info &self, uintptr_t value) { self.gpio3_base = reinterpret_cast<decltype(self.gpio3_base)>(value); });
  cls_Rk3328SocInfo.def_prop_rw("cru_base_address", [](rk3328_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.cru_base); }, [](rk3328_soc_info &self, uintptr_t value) { self.cru_base = reinterpret_cast<decltype(self.cru_base)>(value); });
  cls_Rk3328SocInfo.def_prop_rw("grf_base_address", [](rk3328_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.grf_base); }, [](rk3328_soc_info &self, uintptr_t value) { self.grf_base = reinterpret_cast<decltype(self.grf_base)>(value); });
  auto cls_S905d3GPIOInfo = nb::class_<s905d3_gpio_info>(m, "S905d3GPIOInfo").def(nb::init<>());
  cls_S905d3GPIOInfo.def_prop_rw("gpio_base_address", [](s905d3_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base); }, [](s905d3_gpio_info &self, uintptr_t value) { self.gpio_base = reinterpret_cast<decltype(self.gpio_base)>(value); });
  cls_S905d3GPIOInfo.def_prop_rw("gpio_ao_base_address", [](s905d3_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_ao_base); }, [](s905d3_gpio_info &self, uintptr_t value) { self.gpio_ao_base = reinterpret_cast<decltype(self.gpio_ao_base)>(value); });
  cls_S905d3GPIOInfo.def_prop_rw("gpio_pwm_base_address", [](s905d3_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_pwm_base); }, [](s905d3_gpio_info &self, uintptr_t value) { self.gpio_pwm_base = reinterpret_cast<decltype(self.gpio_pwm_base)>(value); });
  cls_S905d3GPIOInfo.def_prop_rw("gpio_pwm_ao_base_address", [](s905d3_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_pwm_ao_base); }, [](s905d3_gpio_info &self, uintptr_t value) { self.gpio_pwm_ao_base = reinterpret_cast<decltype(self.gpio_pwm_ao_base)>(value); });
  cls_S905d3GPIOInfo.def_rw("gpio_out_en", &s905d3_gpio_info::gpio_out_en);
  cls_S905d3GPIOInfo.def_rw("gpio_out", &s905d3_gpio_info::gpio_out);
  cls_S905d3GPIOInfo.def_rw("gpio_in", &s905d3_gpio_info::gpio_in);
  cls_S905d3GPIOInfo.def_rw("gpio_pupd", &s905d3_gpio_info::gpio_pupd);
  cls_S905d3GPIOInfo.def_rw("gpio_puen", &s905d3_gpio_info::gpio_puen);
  cls_S905d3GPIOInfo.def_rw("gpio_mux", &s905d3_gpio_info::gpio_mux);
  cls_S905d3GPIOInfo.def_rw("gpio_out_en_offset", &s905d3_gpio_info::gpio_out_en_offset);
  cls_S905d3GPIOInfo.def_rw("gpio_out_offset", &s905d3_gpio_info::gpio_out_offset);
  cls_S905d3GPIOInfo.def_rw("gpio_in_offset", &s905d3_gpio_info::gpio_in_offset);
  cls_S905d3GPIOInfo.def_rw("gpio_pupd_offset", &s905d3_gpio_info::gpio_pupd_offset);
  cls_S905d3GPIOInfo.def_rw("gpio_puen_offset", &s905d3_gpio_info::gpio_puen_offset);
  cls_S905d3GPIOInfo.def_rw("gpio_mux_offset", &s905d3_gpio_info::gpio_mux_offset);
  cls_S905d3GPIOInfo.def_rw("pwm_duty_cycle", &s905d3_gpio_info::pwm_duty_cycle);
  cls_S905d3GPIOInfo.def_rw("pwm_misc", &s905d3_gpio_info::pwm_misc);
  auto cls_A310bGPIOInfo = nb::class_<a310b_gpio_info>(m, "A310bGPIOInfo").def(nb::init<>());
  cls_A310bGPIOInfo.def_prop_rw("iomux_base_group0_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group0); }, [](a310b_gpio_info &self, uintptr_t value) { self.iomux_base_group0 = reinterpret_cast<decltype(self.iomux_base_group0)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("iomux_base_group1_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group1); }, [](a310b_gpio_info &self, uintptr_t value) { self.iomux_base_group1 = reinterpret_cast<decltype(self.iomux_base_group1)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("iomux_base_group2_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group2); }, [](a310b_gpio_info &self, uintptr_t value) { self.iomux_base_group2 = reinterpret_cast<decltype(self.iomux_base_group2)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("iomux_base_group3_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group3); }, [](a310b_gpio_info &self, uintptr_t value) { self.iomux_base_group3 = reinterpret_cast<decltype(self.iomux_base_group3)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("iomux_base_group4_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group4); }, [](a310b_gpio_info &self, uintptr_t value) { self.iomux_base_group4 = reinterpret_cast<decltype(self.iomux_base_group4)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("iomux_base_group5_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group5); }, [](a310b_gpio_info &self, uintptr_t value) { self.iomux_base_group5 = reinterpret_cast<decltype(self.iomux_base_group5)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("iomux_base_group7_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group7); }, [](a310b_gpio_info &self, uintptr_t value) { self.iomux_base_group7 = reinterpret_cast<decltype(self.iomux_base_group7)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("gpio_base_group0_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group0); }, [](a310b_gpio_info &self, uintptr_t value) { self.gpio_base_group0 = reinterpret_cast<decltype(self.gpio_base_group0)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("gpio_base_group1_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group1); }, [](a310b_gpio_info &self, uintptr_t value) { self.gpio_base_group1 = reinterpret_cast<decltype(self.gpio_base_group1)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("gpio_base_group2_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group2); }, [](a310b_gpio_info &self, uintptr_t value) { self.gpio_base_group2 = reinterpret_cast<decltype(self.gpio_base_group2)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("gpio_base_group3_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group3); }, [](a310b_gpio_info &self, uintptr_t value) { self.gpio_base_group3 = reinterpret_cast<decltype(self.gpio_base_group3)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("gpio_base_group4_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group4); }, [](a310b_gpio_info &self, uintptr_t value) { self.gpio_base_group4 = reinterpret_cast<decltype(self.gpio_base_group4)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("gpio_base_group5_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group5); }, [](a310b_gpio_info &self, uintptr_t value) { self.gpio_base_group5 = reinterpret_cast<decltype(self.gpio_base_group5)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("gpio_base_group7_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group7); }, [](a310b_gpio_info &self, uintptr_t value) { self.gpio_base_group7 = reinterpret_cast<decltype(self.gpio_base_group7)>(value); });
  cls_A310bGPIOInfo.def_prop_rw("pwm_base_address", [](a310b_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm_base); }, [](a310b_gpio_info &self, uintptr_t value) { self.pwm_base = reinterpret_cast<decltype(self.pwm_base)>(value); });
  cls_A310bGPIOInfo.def_rw("pwm_prd2_phyaddr", &a310b_gpio_info::pwm_prd2_phyaddr);
  cls_A310bGPIOInfo.def_rw("pwm_ch2_pwl_phyaddr", &a310b_gpio_info::pwm_ch2_pwl_phyaddr);
  cls_A310bGPIOInfo.def_rw("pwm_ch2_pwh_phyaddr", &a310b_gpio_info::pwm_ch2_pwh_phyaddr);
  cls_A310bGPIOInfo.def_rw("pwm_prd3_phyaddr", &a310b_gpio_info::pwm_prd3_phyaddr);
  cls_A310bGPIOInfo.def_rw("pwm_ch3_pwl_phyaddr", &a310b_gpio_info::pwm_ch3_pwl_phyaddr);
  cls_A310bGPIOInfo.def_rw("pwm_ch3_pwh_phyaddr", &a310b_gpio_info::pwm_ch3_pwh_phyaddr);
  cls_A310bGPIOInfo.def_rw("pwm_measure_time_phyaddr", &a310b_gpio_info::pwm_measure_time_phyaddr);
  auto cls_A310pGPIOInfo = nb::class_<a310p_gpio_info>(m, "A310pGPIOInfo").def(nb::init<>());
  cls_A310pGPIOInfo.def_prop_rw("iomux_base_group0_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group0); }, [](a310p_gpio_info &self, uintptr_t value) { self.iomux_base_group0 = reinterpret_cast<decltype(self.iomux_base_group0)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("iomux_base_group1_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group1); }, [](a310p_gpio_info &self, uintptr_t value) { self.iomux_base_group1 = reinterpret_cast<decltype(self.iomux_base_group1)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("iomux_base_group2_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group2); }, [](a310p_gpio_info &self, uintptr_t value) { self.iomux_base_group2 = reinterpret_cast<decltype(self.iomux_base_group2)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("iomux_base_group3_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group3); }, [](a310p_gpio_info &self, uintptr_t value) { self.iomux_base_group3 = reinterpret_cast<decltype(self.iomux_base_group3)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("iomux_base_group4_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group4); }, [](a310p_gpio_info &self, uintptr_t value) { self.iomux_base_group4 = reinterpret_cast<decltype(self.iomux_base_group4)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("iomux_base_group5_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base_group5); }, [](a310p_gpio_info &self, uintptr_t value) { self.iomux_base_group5 = reinterpret_cast<decltype(self.iomux_base_group5)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("gpio_base_group0_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group0); }, [](a310p_gpio_info &self, uintptr_t value) { self.gpio_base_group0 = reinterpret_cast<decltype(self.gpio_base_group0)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("gpio_base_group1_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group1); }, [](a310p_gpio_info &self, uintptr_t value) { self.gpio_base_group1 = reinterpret_cast<decltype(self.gpio_base_group1)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("gpio_base_group2_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group2); }, [](a310p_gpio_info &self, uintptr_t value) { self.gpio_base_group2 = reinterpret_cast<decltype(self.gpio_base_group2)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("gpio_base_group3_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group3); }, [](a310p_gpio_info &self, uintptr_t value) { self.gpio_base_group3 = reinterpret_cast<decltype(self.gpio_base_group3)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("gpio_base_group4_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group4); }, [](a310p_gpio_info &self, uintptr_t value) { self.gpio_base_group4 = reinterpret_cast<decltype(self.gpio_base_group4)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("gpio_base_group5_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base_group5); }, [](a310p_gpio_info &self, uintptr_t value) { self.gpio_base_group5 = reinterpret_cast<decltype(self.gpio_base_group5)>(value); });
  cls_A310pGPIOInfo.def_prop_rw("pwm_base_address", [](a310p_gpio_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwm_base); }, [](a310p_gpio_info &self, uintptr_t value) { self.pwm_base = reinterpret_cast<decltype(self.pwm_base)>(value); });
  cls_A310pGPIOInfo.def_rw("pwm_prd1_phyaddr", &a310p_gpio_info::pwm_prd1_phyaddr);
  cls_A310pGPIOInfo.def_rw("pwm_ch1_pwl_phyaddr", &a310p_gpio_info::pwm_ch1_pwl_phyaddr);
  cls_A310pGPIOInfo.def_rw("pwm_ch1_pwh_phyaddr", &a310p_gpio_info::pwm_ch1_pwh_phyaddr);
  cls_A310pGPIOInfo.def_rw("pwm_measure_time_phyaddr", &a310p_gpio_info::pwm_measure_time_phyaddr);
  auto cls_Jh7110SocInfo = nb::class_<jh7110_soc_info>(m, "Jh7110SocInfo").def(nb::init<>());
  cls_Jh7110SocInfo.def_prop_rw("sys_iomux_base_address", [](jh7110_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.sys_iomux_base); }, [](jh7110_soc_info &self, uintptr_t value) { self.sys_iomux_base = reinterpret_cast<decltype(self.sys_iomux_base)>(value); });
  auto cls_Kyx1SocInfo = nb::class_<kyx1_soc_info>(m, "Kyx1SocInfo").def(nb::init<>());
  cls_Kyx1SocInfo.def_prop_rw("iomux_base_address", [](kyx1_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.iomux_base); }, [](kyx1_soc_info &self, uintptr_t value) { self.iomux_base = reinterpret_cast<decltype(self.iomux_base)>(value); });
  cls_Kyx1SocInfo.def_prop_rw("gpio_base_address", [](kyx1_soc_info &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.gpio_base); }, [](kyx1_soc_info &self, uintptr_t value) { self.gpio_base = reinterpret_cast<decltype(self.gpio_base)>(value); });
  auto cls_WiringPiNodeStruct = nb::class_<wiringPiNodeStruct>(m, "WiringPiNodeStruct").def(nb::init<>());
  cls_WiringPiNodeStruct.def_rw("pin_base", &wiringPiNodeStruct::pinBase);
  cls_WiringPiNodeStruct.def_rw("pin_max", &wiringPiNodeStruct::pinMax);
  cls_WiringPiNodeStruct.def_rw("fd", &wiringPiNodeStruct::fd);
  cls_WiringPiNodeStruct.def_rw("data0", &wiringPiNodeStruct::data0);
  cls_WiringPiNodeStruct.def_rw("data1", &wiringPiNodeStruct::data1);
  cls_WiringPiNodeStruct.def_rw("data2", &wiringPiNodeStruct::data2);
  cls_WiringPiNodeStruct.def_rw("data3", &wiringPiNodeStruct::data3);
  cls_WiringPiNodeStruct.def_prop_rw("pin_mode_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pinMode); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.pinMode = reinterpret_cast<decltype(self.pinMode)>(value); });
  cls_WiringPiNodeStruct.def_prop_rw("pull_up_dn_control_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pullUpDnControl); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.pullUpDnControl = reinterpret_cast<decltype(self.pullUpDnControl)>(value); });
  cls_WiringPiNodeStruct.def_prop_rw("digital_read_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.digitalRead); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.digitalRead = reinterpret_cast<decltype(self.digitalRead)>(value); });
  cls_WiringPiNodeStruct.def_prop_rw("digital_write_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.digitalWrite); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.digitalWrite = reinterpret_cast<decltype(self.digitalWrite)>(value); });
  cls_WiringPiNodeStruct.def_prop_rw("pwm_write_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.pwmWrite); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.pwmWrite = reinterpret_cast<decltype(self.pwmWrite)>(value); });
  cls_WiringPiNodeStruct.def_prop_rw("analog_read_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.analogRead); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.analogRead = reinterpret_cast<decltype(self.analogRead)>(value); });
  cls_WiringPiNodeStruct.def_prop_rw("analog_write_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.analogWrite); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.analogWrite = reinterpret_cast<decltype(self.analogWrite)>(value); });
  cls_WiringPiNodeStruct.def_prop_rw("next_address", [](wiringPiNodeStruct &self) -> uintptr_t { return reinterpret_cast<uintptr_t>(self.next); }, [](wiringPiNodeStruct &self, uintptr_t value) { self.next = reinterpret_cast<decltype(self.next)>(value); });
  m.def("pi_gpio_layout_oops", &piGpioLayoutOops, nb::arg("why"));
  m.def("wiring_pi_failure", [](int fatal, const char *message) { return wiringPiFailure(fatal, "%s", message); }, nb::arg("fatal"), nb::arg("message"));
  m.def("wiring_pi_find_node", &wiringPiFindNode, nb::rv_policy::reference, nb::arg("pin"));
  m.def("wiring_pi_new_node", &wiringPiNewNode, nb::rv_policy::reference, nb::arg("pin_base"), nb::arg("num_pins"));
  m.def("wiring_pi_version", []() { int major=0; int minor=0; wiringPiVersion(&major, &minor); return nb::make_tuple(major, minor); });
  m.def("wiring_pi_setup", &wiringPiSetup);
  m.def("wiring_pi_setup_sys", &wiringPiSetupSys);
  m.def("wiring_pi_setup_gpio", &wiringPiSetupGpio);
  m.def("wiring_pi_setup_phys", &wiringPiSetupPhys);
  m.def("pin_mode_alt", &pinModeAlt, nb::arg("pin"), nb::arg("mode"));
  m.def("pin_mode", &pinMode, nb::arg("pin"), nb::arg("mode"));
  m.def("pull_up_dn_control", &pullUpDnControl, nb::arg("pin"), nb::arg("pud"));
  m.def("digital_read", &digitalRead, nb::arg("pin"));
  m.def("digital_write", &digitalWrite, nb::arg("pin"), nb::arg("value"));
  m.def("digital_read8", [](int pin) -> unsigned int { (void)pin; PyErr_SetString(PyExc_NotImplementedError, "digitalRead8 is declared by wiringOP but not implemented in this revision"); throw nb::python_error(); }, nb::arg("pin"));
  m.def("digital_write8", [](int pin, int value) { (void)pin; (void)value; PyErr_SetString(PyExc_NotImplementedError, "digitalWrite8 is declared by wiringOP but not implemented in this revision"); throw nb::python_error(); }, nb::arg("pin"), nb::arg("value"));
  m.def("pwm_write", &pwmWrite, nb::arg("pin"), nb::arg("value"));
  m.def("analog_read", &analogRead, nb::arg("pin"));
  m.def("analog_write", &analogWrite, nb::arg("pin"), nb::arg("value"));
  m.def("wiring_pi_setup_pi_face", []() -> int {  PyErr_SetString(PyExc_NotImplementedError, "wiringPiSetupPiFace is declared by wiringOP but not implemented in this revision"); throw nb::python_error(); });
  m.def("wiring_pi_setup_pi_face_for_gpio_prog", []() -> int {  PyErr_SetString(PyExc_NotImplementedError, "wiringPiSetupPiFaceForGpioProg is declared by wiringOP but not implemented in this revision"); throw nb::python_error(); });
  m.def("pi_board_id", []() { int model=0; piBoardId(&model); return model; });
  m.def("wpi_pin_to_gpio", &wpiPinToGpio, nb::arg("wpi_pin"));
  m.def("phys_pin_to_gpio", &physPinToGpio, nb::arg("phys_pin"));
  m.def("set_pad_drive", &setPadDrive, nb::arg("group"), nb::arg("value"));
  m.def("get_alt", &getAlt, nb::arg("pin"));
  m.def("h618_set_pwm_reg", &H618_set_pwm_reg, nb::arg("pin"), nb::arg("sunxi_gpio_info_ptr"));
  m.def("s905d3_set_gpio_reg", &s905d3_set_gpio_reg, nb::arg("pin"), nb::arg("s905d3_gpio_info_ptr"));
  m.def("rk3588_set_pwm_reg", &rk3588_set_pwm_reg, nb::arg("pin"), nb::arg("rk3588_soc_info_ptr"));
  m.def("rk3566_set_pwm_reg", &rk3566_set_pwm_reg, nb::arg("pin"), nb::arg("rk3566_soc_info_ptr"));
  m.def("sunxi_pwm_set_enable", &sunxi_pwm_set_enable, nb::arg("en"));
  m.def("pwm_tone_write", &pwmToneWrite, nb::arg("pin"), nb::arg("freq"));
  m.def("pwm_set_mode", &pwmSetMode, nb::arg("pin"), nb::arg("mode"));
  m.def("pwm_set_range", &pwmSetRange, nb::arg("pin"), nb::arg("range"));
  m.def("pwm_set_clock", &pwmSetClock, nb::arg("pin"), nb::arg("divisor"));
  m.def("gpio_clock_set", &gpioClockSet, nb::arg("pin"), nb::arg("freq"));
  m.def("digital_read_byte", &digitalReadByte);
  m.def("digital_read_byte2", &digitalReadByte2);
  m.def("digital_write_byte", &digitalWriteByte, nb::arg("value"));
  m.def("digital_write_byte2", &digitalWriteByte2, nb::arg("value"));
  m.def("wait_for_interrupt", &waitForInterrupt, nb::arg("pin"), nb::arg("m_s"));
  m.def("wiring_pi_isr", [](int pin,int mode,nb::callable cb) { if(pin<0||pin>=MAX_PIN_NUM) throw nb::value_error("pin is outside MAX_PIN_NUM"); std::lock_guard<std::mutex> lock(g_isr_mutex); PyObject *q=cb.ptr(); Py_INCREF(q); Py_XDECREF(g_isr_callbacks[pin]); g_isr_callbacks[pin]=q; int rc=wiringPiISR(pin,mode,isr_fn((size_t)pin)); if(rc<0) Py_CLEAR(g_isr_callbacks[pin]); return rc; }, nb::arg("pin"), nb::arg("mode"), nb::arg("callback"));
  m.def("pi_thread_create", [](nb::callable cb) { size_t slot=16; { std::lock_guard<std::mutex> lock(g_thread_mutex); for(size_t i=0;i<16;++i) if(!g_thread_callbacks[i]){slot=i;Py_INCREF(cb.ptr());g_thread_callbacks[i]=cb.ptr();break;} } if(slot==16) throw std::runtime_error("no free callback slots"); int rc=piThreadCreate(thread_fn(slot)); if(rc<0){std::lock_guard<std::mutex> lock(g_thread_mutex);Py_CLEAR(g_thread_callbacks[slot]);} return rc; }, nb::arg("callback"));
  m.def("pi_lock", &piLock, nb::arg("key"));
  m.def("pi_unlock", &piUnlock, nb::arg("key"));
  m.def("pi_hi_pri", &piHiPri, nb::arg("pri"));
  m.def("delay", &delay, nb::arg("how_long"));
  m.def("delay_microseconds", &delayMicroseconds, nb::arg("how_long"));
  m.def("millis", &millis);
  m.def("micros", &micros);
  m.def("read_r", &readR, nb::arg("addr"));
  m.def("write_r", &writeR, nb::arg("val"), nb::arg("addr"));
  m.def("orangepi_get_gpio_mode", &orangepi_get_gpio_mode, nb::arg("pin"));
  m.def("orangepi_set_gpio_mode", &orangepi_set_gpio_mode, nb::arg("pin"), nb::arg("mode"));
  m.def("orangepi_digital_read", &orangepi_digitalRead, nb::arg("pin"));
  m.def("orangepi_digital_write", &orangepi_digitalWrite, nb::arg("pin"), nb::arg("value"));
  m.def("orangepi_set_gpio_alt", &orangepi_set_gpio_alt, nb::arg("pin"), nb::arg("mode"));
  m.def("orange_pi_set_gpio_pull_up_dn_control", &OrangePi_set_gpio_pullUpDnControl, nb::arg("pin"), nb::arg("pud"));
  m.def("orangepi_pwm_set_act", &orangepi_pwm_set_act, nb::arg("pin"), nb::arg("act_cys"));
  m.def("orangepi_pwm_set_period", &orangepi_pwm_set_period, nb::arg("pin"), nb::arg("period_cys"));
  m.def("orangepi_pwm_set_clk", &orangepi_pwm_set_clk, nb::arg("pin"), nb::arg("clk"));
  m.def("orangepi_pwm_set_tone", &orangepi_pwm_set_tone, nb::arg("pin"), nb::arg("freq"));
  m.def("set_soc_info", &set_soc_info);
  m.def("get_wiring_pi_debug", []() { return wiringPiDebug; });
  m.def("set_wiring_pi_debug", [](decltype(wiringPiDebug) value) { wiringPiDebug=value; }, nb::arg("value"));
  { void *sym=dlsym(RTLD_DEFAULT,"piModelNames"); if(sym){ const char * const *p=reinterpret_cast<const char * const *>(sym); nb::list x; for(size_t i=0;i<16;++i)x.append(p[i]?nb::str(p[i]):nb::none()); m.attr("pi_model_names")=nb::tuple(x); } else m.attr("pi_model_names")=nb::none(); }
  { void *sym=dlsym(RTLD_DEFAULT,"piRevisionNames"); if(sym){ const char * const *p=reinterpret_cast<const char * const *>(sym); nb::list x; for(size_t i=0;i<16;++i)x.append(p[i]?nb::str(p[i]):nb::none()); m.attr("pi_revision_names")=nb::tuple(x); } else m.attr("pi_revision_names")=nb::none(); }
  { void *sym=dlsym(RTLD_DEFAULT,"piMakerNames"); if(sym){ const char * const *p=reinterpret_cast<const char * const *>(sym); nb::list x; for(size_t i=0;i<16;++i)x.append(p[i]?nb::str(p[i]):nb::none()); m.attr("pi_maker_names")=nb::tuple(x); } else m.attr("pi_maker_names")=nb::none(); }
  { void *sym=dlsym(RTLD_DEFAULT,"piMemorySize"); if(sym){ const int *p=reinterpret_cast<const int *>(sym); nb::list x; for(size_t i=0;i<8;++i)x.append(p[i]); m.attr("pi_memory_size")=nb::tuple(x); } else m.attr("pi_memory_size")=nb::none(); }
  m.def("get_wiring_pi_nodes_address", []() -> uintptr_t { return reinterpret_cast<uintptr_t>(wiringPiNodes); });
  m.def("set_wiring_pi_nodes_address", [](uintptr_t value) { wiringPiNodes=reinterpret_cast<decltype(wiringPiNodes)>(value); }, nb::arg("address"));
  m.def("get_wiring_pi_gpio_address", []() -> uintptr_t { return reinterpret_cast<uintptr_t>(_wiringPiGpio); });
  m.def("set_wiring_pi_gpio_address", [](uintptr_t value) { _wiringPiGpio=reinterpret_cast<decltype(_wiringPiGpio)>(value); }, nb::arg("address"));
  m.def("get_wiring_pi_pwm_address", []() -> uintptr_t { return reinterpret_cast<uintptr_t>(_wiringPiPwm); });
  m.def("set_wiring_pi_pwm_address", [](uintptr_t value) { _wiringPiPwm=reinterpret_cast<decltype(_wiringPiPwm)>(value); }, nb::arg("address"));
  m.def("get_wiring_pi_clk_address", []() -> uintptr_t { return reinterpret_cast<uintptr_t>(_wiringPiClk); });
  m.def("set_wiring_pi_clk_address", [](uintptr_t value) { _wiringPiClk=reinterpret_cast<decltype(_wiringPiClk)>(value); }, nb::arg("address"));
  m.def("get_wiring_pi_pads_address", []() -> uintptr_t { return reinterpret_cast<uintptr_t>(_wiringPiPads); });
  m.def("set_wiring_pi_pads_address", [](uintptr_t value) { _wiringPiPads=reinterpret_cast<decltype(_wiringPiPads)>(value); }, nb::arg("address"));
  m.def("get_wiring_pi_timer_address", []() -> uintptr_t { return reinterpret_cast<uintptr_t>(_wiringPiTimer); });
  m.def("set_wiring_pi_timer_address", [](uintptr_t value) { _wiringPiTimer=reinterpret_cast<decltype(_wiringPiTimer)>(value); }, nb::arg("address"));
  m.def("get_wiring_pi_timer_irq_raw_address", []() -> uintptr_t { return reinterpret_cast<uintptr_t>(_wiringPiTimerIrqRaw); });
  m.def("set_wiring_pi_timer_irq_raw_address", [](uintptr_t value) { _wiringPiTimerIrqRaw=reinterpret_cast<decltype(_wiringPiTimerIrqRaw)>(value); }, nb::arg("address"));
  m.attr("TRUE")=nb::cast((TRUE));
  m.attr("FALSE")=nb::cast((FALSE));
  m.attr("MAX_PIN_NUM")=nb::cast((MAX_PIN_NUM));
  m.attr("PI_MODEL_A")=nb::cast((PI_MODEL_A));
  m.attr("PI_MODEL_B")=nb::cast((PI_MODEL_B));
  m.attr("PI_MODEL_AP")=nb::cast((PI_MODEL_AP));
  m.attr("PI_MODEL_BP")=nb::cast((PI_MODEL_BP));
  m.attr("PI_MODEL_2")=nb::cast((PI_MODEL_2));
  m.attr("PI_ALPHA")=nb::cast((PI_ALPHA));
  m.attr("PI_MODEL_CM")=nb::cast((PI_MODEL_CM));
  m.attr("PI_MODEL_07")=nb::cast((PI_MODEL_07));
  m.attr("PI_MODEL_CM3")=nb::cast((PI_MODEL_CM3));
  m.attr("PI_MODEL_ZERO_W")=nb::cast((PI_MODEL_ZERO_W));
  m.attr("PI_MODEL_3_P")=nb::cast((PI_MODEL_3P));
  m.attr("PI_VERSION_1")=nb::cast((PI_VERSION_1));
  m.attr("PI_VERSION_1_1")=nb::cast((PI_VERSION_1_1));
  m.attr("PI_VERSION_1_2")=nb::cast((PI_VERSION_1_2));
  m.attr("PI_VERSION_2")=nb::cast((PI_VERSION_2));
  m.attr("PI_MAKER_SONY")=nb::cast((PI_MAKER_SONY));
  m.attr("PI_MAKER_EGOMAN")=nb::cast((PI_MAKER_EGOMAN));
  m.attr("PI_MAKER_EMBEST")=nb::cast((PI_MAKER_EMBEST));
  m.attr("PI_MAKER_UNKNOWN")=nb::cast((PI_MAKER_UNKNOWN));
  m.attr("H3_GPIO_BASE_ADDR")=nb::cast((H3_GPIO_BASE_ADDR));
  m.attr("H3_R_GPIO_BASE_ADDR")=nb::cast((H3_R_GPIO_BASE_ADDR));
  m.attr("H6_GPIO_BASE_ADDR")=nb::cast((H6_GPIO_BASE_ADDR));
  m.attr("H6_R_GPIO_BASE_ADDR")=nb::cast((H6_R_GPIO_BASE_ADDR));
  m.attr("A527_GPIO_BASE_ADDR")=nb::cast((A527_GPIO_BASE_ADDR));
  m.attr("T736_R_GPIO_BASE_ADDR")=nb::cast((T736_R_GPIO_BASE_ADDR));
  m.attr("H3_PWM_BASE")=nb::cast((H3_PWM_BASE));
  m.attr("H6_PWM_BASE")=nb::cast((H6_PWM_BASE));
  m.attr("H616_PWM_BASE")=nb::cast((H616_PWM_BASE));
  m.attr("SUNXI_V1_PWM_TYPE")=nb::cast((SUNXI_V1_PWM_TYPE));
  m.attr("SUNXI_V2_PWM_TYPE")=nb::cast((SUNXI_V2_PWM_TYPE));
  m.attr("SUNXI_V1_PWM_CH0_EN")=nb::cast((SUNXI_V1_PWM_CH0_EN));
  m.attr("SUNXI_V1_PWM_CH0_ACT_STA")=nb::cast((SUNXI_V1_PWM_CH0_ACT_STA));
  m.attr("SUNXI_V1_PWM_SCLK_CH0_GATING")=nb::cast((SUNXI_V1_PWM_SCLK_CH0_GATING));
  m.attr("SUNXI_V1_PWM_CH0_MS_MODE")=nb::cast((SUNXI_V1_PWM_CH0_MS_MODE));
  m.attr("SUNXI_V1_PWM_CH0_PUL_START")=nb::cast((SUNXI_V1_PWM_CH0_PUL_START));
  m.attr("SUNXI_V2_PWM_ACT_STA")=nb::cast((SUNXI_V2_PWM_ACT_STA));
  m.attr("SUNXI_V2_PWM_SCLK_GATING")=nb::cast((SUNXI_V2_PWM_SCLK_GATING));
  m.attr("SUNXI_V2_PWM_MS_MODE")=nb::cast((SUNXI_V2_PWM_MS_MODE));
  m.attr("SUNXI_V2_PWM_PUL_START")=nb::cast((SUNXI_V2_PWM_PUL_START));
  m.attr("SUNXI_V2_PWM1_EN")=nb::cast((SUNXI_V2_PWM1_EN));
  m.attr("SUNXI_V2_PWM2_EN")=nb::cast((SUNXI_V2_PWM2_EN));
  m.attr("SUNXI_V2_PWM3_EN")=nb::cast((SUNXI_V2_PWM3_EN));
  m.attr("SUNXI_V2_PWM4_EN")=nb::cast((SUNXI_V2_PWM4_EN));
  m.attr("PWM_CLK_DIV_120")=nb::cast((PWM_CLK_DIV_120));
  m.attr("PWM_CLK_DIV_180")=nb::cast((PWM_CLK_DIV_180));
  m.attr("PWM_CLK_DIV_240")=nb::cast((PWM_CLK_DIV_240));
  m.attr("PWM_CLK_DIV_360")=nb::cast((PWM_CLK_DIV_360));
  m.attr("PWM_CLK_DIV_480")=nb::cast((PWM_CLK_DIV_480));
  m.attr("PWM_CLK_DIV_12_K")=nb::cast((PWM_CLK_DIV_12K));
  m.attr("PWM_CLK_DIV_24_K")=nb::cast((PWM_CLK_DIV_24K));
  m.attr("PWM_CLK_DIV_36_K")=nb::cast((PWM_CLK_DIV_36K));
  m.attr("PWM_CLK_DIV_48_K")=nb::cast((PWM_CLK_DIV_48K));
  m.attr("PWM_CLK_DIV_72_K")=nb::cast((PWM_CLK_DIV_72K));
  m.attr("SUNXI_PUD_OFF")=nb::cast((SUNXI_PUD_OFF));
  m.attr("SUNXI_PUD_UP")=nb::cast((SUNXI_PUD_UP));
  m.attr("SUNXI_PUD_DOWN")=nb::cast((SUNXI_PUD_DOWN));
  m.attr("RK3588_GPIO0_BASE")=nb::cast((RK3588_GPIO0_BASE));
  m.attr("RK3588_GPIO1_BASE")=nb::cast((RK3588_GPIO1_BASE));
  m.attr("RK3588_GPIO2_BASE")=nb::cast((RK3588_GPIO2_BASE));
  m.attr("RK3588_GPIO3_BASE")=nb::cast((RK3588_GPIO3_BASE));
  m.attr("RK3588_GPIO4_BASE")=nb::cast((RK3588_GPIO4_BASE));
  m.attr("RK3588_GPIO_SWPORT_DR_L_OFFSET")=nb::cast((RK3588_GPIO_SWPORT_DR_L_OFFSET));
  m.attr("RK3588_GPIO_SWPORT_DR_H_OFFSET")=nb::cast((RK3588_GPIO_SWPORT_DR_H_OFFSET));
  m.attr("RK3588_GPIO_SWPORT_DDR_L_OFFSET")=nb::cast((RK3588_GPIO_SWPORT_DDR_L_OFFSET));
  m.attr("RK3588_GPIO_SWPORT_DDR_H_OFFSET")=nb::cast((RK3588_GPIO_SWPORT_DDR_H_OFFSET));
  m.attr("RK3588_GPIO_EXT_PORT_OFFSET")=nb::cast((RK3588_GPIO_EXT_PORT_OFFSET));
  m.attr("RK3588_CRU_BASE")=nb::cast((RK3588_CRU_BASE));
  m.attr("RK3588_CRU_GATE_CON16_OFFSET")=nb::cast((RK3588_CRU_GATE_CON16_OFFSET));
  m.attr("RK3588_CRU_GATE_CON17_OFFSET")=nb::cast((RK3588_CRU_GATE_CON17_OFFSET));
  m.attr("RK3588_PMU1_CRU_BASE")=nb::cast((RK3588_PMU1CRU_BASE));
  m.attr("RK3588_PMU1_CRU_GATE_CON5_OFFSET")=nb::cast((RK3588_PMU1CRU_GATE_CON5_OFFSET));
  m.attr("RK3588_GPIO_NUM")=nb::cast((RK3588_GPIO_NUM));
  m.def("RK3588_GPIO_BIT", [](int x) { return RK3588_GPIO_BIT(x); }, nb::arg("x"));
  m.attr("RK3588_PMU1_IOC_BASE")=nb::cast((RK3588_PMU1_IOC_BASE));
  m.attr("RK3588_PMU1_IOC_GPIO0_A_IOMUX_SEL_L")=nb::cast((RK3588_PMU1_IOC_GPIO0A_IOMUX_SEL_L));
  m.attr("RK3588_PMU1_IOC_GPIO0_A_IOMUX_SEL_H")=nb::cast((RK3588_PMU1_IOC_GPIO0A_IOMUX_SEL_H));
  m.attr("RK3588_PMU1_IOC_GPIO0_B_IOMUX_SEL_L")=nb::cast((RK3588_PMU1_IOC_GPIO0B_IOMUX_SEL_L));
  m.attr("RK3588_PMU2_IOC_BASE")=nb::cast((RK3588_PMU2_IOC_BASE));
  m.attr("RK3588_PMU2_IOC_GPIO0_B_IOMUX_SEL_H")=nb::cast((RK3588_PMU2_IOC_GPIO0B_IOMUX_SEL_H));
  m.attr("RK3588_PMU2_IOC_GPIO0_C_IOMUX_SEL_L")=nb::cast((RK3588_PMU2_IOC_GPIO0C_IOMUX_SEL_L));
  m.attr("RK3588_PMU2_IOC_GPIO0_C_IOMUX_SEL_H")=nb::cast((RK3588_PMU2_IOC_GPIO0C_IOMUX_SEL_H));
  m.attr("RK3588_PMU2_IOC_GPIO0_D_IOMUX_SEL_L")=nb::cast((RK3588_PMU2_IOC_GPIO0D_IOMUX_SEL_L));
  m.attr("RK3588_PMU2_IOC_GPIO0_D_IOMUX_SEL_H")=nb::cast((RK3588_PMU2_IOC_GPIO0D_IOMUX_SEL_H));
  m.attr("RK3588_BUS_IOC_BASE")=nb::cast((RK3588_BUS_IOC_BASE));
  m.attr("RK3588_VCCIO1_4_IOC_BASE")=nb::cast((RK3588_VCCIO1_4_IOC_BASE));
  m.attr("RK3588_VCCIO3_5_IOC_BASE")=nb::cast((RK3588_VCCIO3_5_IOC_BASE));
  m.attr("RK3588_VCCIO6_IOC_BASE")=nb::cast((RK3588_VCCIO6_IOC_BASE));
  m.attr("RK3588_PMU1_IOC_GPIO0_A_P")=nb::cast((RK3588_PMU1_IOC_GPIO0A_P));
  m.attr("RK3588_PMU1_IOC_GPIO0_B_P")=nb::cast((RK3588_PMU1_IOC_GPIO0B_P));
  m.attr("RK3588_PMU2_IOC_GPIO0_B_P")=nb::cast((RK3588_PMU2_IOC_GPIO0B_P));
  m.attr("RK3588_PMU2_IOC_GPIO0_C_P")=nb::cast((RK3588_PMU2_IOC_GPIO0C_P));
  m.attr("RK3588_PMU2_IOC_GPIO0_D_P")=nb::cast((RK3588_PMU2_IOC_GPIO0D_P));
  m.attr("RK3588_VCCIO1_4_IOC_GPIO1_A_P")=nb::cast((RK3588_VCCIO1_4_IOC_GPIO1A_P));
  m.attr("RK3588_VCCIO3_5_IOC_GPIO2_A_P")=nb::cast((RK3588_VCCIO3_5_IOC_GPIO2A_P));
  m.attr("RK3588_VCCIO6_IOC_GPIO4_A_P")=nb::cast((RK3588_VCCIO6_IOC_GPIO4A_P));
  m.attr("RK3588_PWM0_BASE")=nb::cast((RK3588_PWM0_BASE));
  m.attr("RK3588_PWM1_BASE")=nb::cast((RK3588_PWM1_BASE));
  m.attr("RK3588_PWM2_BASE")=nb::cast((RK3588_PWM2_BASE));
  m.attr("RK3588_PWM3_BASE")=nb::cast((RK3588_PWM3_BASE));
  m.attr("RK3588_CRU_GATE_CON19")=nb::cast((RK3588_CRU_GATE_CON19));
  m.attr("RK3588_CRU_GATE_CON15")=nb::cast((RK3588_CRU_GATE_CON15));
  m.attr("RK3588_PMU1_CRU_GATE_CON1")=nb::cast((RK3588_PMU1CRU_GATE_CON1));
  m.attr("RK3588_RPT")=nb::cast((RK3588_RPT));
  m.attr("RK3588_SCALE")=nb::cast((RK3588_SCALE));
  m.attr("RK3588_PRESCALE")=nb::cast((RK3588_PRESCALE));
  m.attr("RK3588_CLK_SRC_SEL")=nb::cast((RK3588_CLK_SRC_SEL));
  m.attr("RK3588_CLK_SEL")=nb::cast((RK3588_CLK_SEL));
  m.attr("RK3588_FORCE_CLK_EN")=nb::cast((RK3588_FORCE_CLK_EN));
  m.attr("RK3588_CH_CNT_EN")=nb::cast((RK3588_CH_CNT_EN));
  m.attr("RK3588_CONLOCK")=nb::cast((RK3588_CONLOCK));
  m.attr("RK3588_OUTPUT_MODE")=nb::cast((RK3588_OUTPUT_MODE));
  m.attr("RK3588_INACTIVE_POL")=nb::cast((RK3588_INACTIVE_POL));
  m.attr("RK3588_DUTY_POL")=nb::cast((RK3588_DUTY_POL));
  m.attr("RK3588_PWM_MODE")=nb::cast((RK3588_PWM_MODE));
  m.attr("RK3588_PWM_EN")=nb::cast((RK3588_PWM_EN));
  m.attr("RK3566_GPIO0_BASE")=nb::cast((RK3566_GPIO0_BASE));
  m.attr("RK3566_GPIO1_BASE")=nb::cast((RK3566_GPIO1_BASE));
  m.attr("RK3566_GPIO2_BASE")=nb::cast((RK3566_GPIO2_BASE));
  m.attr("RK3566_GPIO3_BASE")=nb::cast((RK3566_GPIO3_BASE));
  m.attr("RK3566_GPIO4_BASE")=nb::cast((RK3566_GPIO4_BASE));
  m.attr("RK3566_GPIO_SWPORT_DR_L_OFFSET")=nb::cast((RK3566_GPIO_SWPORT_DR_L_OFFSET));
  m.attr("RK3566_GPIO_SWPORT_DR_H_OFFSET")=nb::cast((RK3566_GPIO_SWPORT_DR_H_OFFSET));
  m.attr("RK3566_GPIO_SWPORT_DDR_L_OFFSET")=nb::cast((RK3566_GPIO_SWPORT_DDR_L_OFFSET));
  m.attr("RK3566_GPIO_SWPORT_DDR_H_OFFSET")=nb::cast((RK3566_GPIO_SWPORT_DDR_H_OFFSET));
  m.attr("RK3566_GPIO_EXT_PORT_OFFSET")=nb::cast((RK3566_GPIO_EXT_PORT_OFFSET));
  m.attr("RK3566_PMU_GRF_BASE")=nb::cast((RK3566_PMU_GRF_BASE));
  m.attr("RK3566_SYS_GRF_BASE")=nb::cast((RK3566_SYS_GRF_BASE));
  m.attr("RK3566_PMU_CRU_BASE")=nb::cast((RK3566_PMU_CRU_BASE));
  m.attr("RK3566_CRU_BASE")=nb::cast((RK3566_CRU_BASE));
  m.attr("RK3566_CRU_GATE_CON31_OFFSET")=nb::cast((RK3566_CRU_GATE_CON31_OFFSET));
  m.attr("RK3566_CRU_GATE_CON31")=nb::cast((RK3566_CRU_GATE_CON31));
  m.attr("RK3566_CRU_GATE_CON32_OFFSET")=nb::cast((RK3566_CRU_GATE_CON32_OFFSET));
  m.attr("RK3566_CRU_GATE_CON32")=nb::cast((RK3566_CRU_GATE_CON32));
  m.attr("RK3566_PMUCRU_PMUGATE_CON01_OFFSET")=nb::cast((RK3566_PMUCRU_PMUGATE_CON01_OFFSET));
  m.attr("RK3566_GRF_GPIO1_A_IOMUX_L_OFFSET")=nb::cast((RK3566_GRF_GPIO1A_IOMUX_L_OFFSET));
  m.attr("RK3566_GRF_GPIO1_A_P_OFFSET")=nb::cast((RK3566_GRF_GPIO1A_P_OFFSET));
  m.attr("RK3566_PMU_GRF_GPIO0_A_IOMUX_L_OFFSET")=nb::cast((RK3566_PMU_GRF_GPIO0A_IOMUX_L_OFFSET));
  m.attr("RK3566_PMU_GRF_GPIO0_A_P_OFFSET")=nb::cast((RK3566_PMU_GRF_GPIO0A_P_OFFSET));
  m.attr("RK3566_PWM_MUX_REG")=nb::cast((RK3566_PWM_MUX_REG));
  m.attr("RK3566_PWM2_BASE")=nb::cast((RK3566_PWM2_BASE));
  m.attr("RK3566_PWM3_BASE")=nb::cast((RK3566_PWM3_BASE));
  m.attr("RK3566_RPT")=nb::cast((RK3566_RPT));
  m.attr("RK3566_SCALE")=nb::cast((RK3566_SCALE));
  m.attr("RK3566_PRESCALE")=nb::cast((RK3566_PRESCALE));
  m.attr("RK3566_CLK_SRC_SEL")=nb::cast((RK3566_CLK_SRC_SEL));
  m.attr("RK3566_CLK_SEL")=nb::cast((RK3566_CLK_SEL));
  m.attr("RK3566_FORCE_CLK_EN")=nb::cast((RK3566_FORCE_CLK_EN));
  m.attr("RK3566_CH_CNT_EN")=nb::cast((RK3566_CH_CNT_EN));
  m.attr("RK3566_CONLOCK")=nb::cast((RK3566_CONLOCK));
  m.attr("RK3566_OUTPUT_MODE")=nb::cast((RK3566_OUTPUT_MODE));
  m.attr("RK3566_INACTIVE_POL")=nb::cast((RK3566_INACTIVE_POL));
  m.attr("RK3566_DUTY_POL")=nb::cast((RK3566_DUTY_POL));
  m.attr("RK3566_PWM_MODE")=nb::cast((RK3566_PWM_MODE));
  m.attr("RK3566_PWM_EN")=nb::cast((RK3566_PWM_EN));
  m.attr("RK3399_GPIO1_BASE")=nb::cast((RK3399_GPIO1_BASE));
  m.attr("RK3399_GPIO2_BASE")=nb::cast((RK3399_GPIO2_BASE));
  m.attr("RK3399_GPIO4_BASE")=nb::cast((RK3399_GPIO4_BASE));
  m.attr("RK3399_GPIO_NUM")=nb::cast((RK3399_GPIO_NUM));
  m.def("RK3399_GPIO_BIT", [](int x) { return RK3399_GPIO_BIT(x); }, nb::arg("x"));
  m.attr("RK3399_GPIO_SWPORTA_DR_OFFSET")=nb::cast((RK3399_GPIO_SWPORTA_DR_OFFSET));
  m.attr("RK3399_GPIO_SWPORTA_DDR_OFFSET")=nb::cast((RK3399_GPIO_SWPORTA_DDR_OFFSET));
  m.attr("RK3399_GPIO_EXT_PORTA_OFFSET")=nb::cast((RK3399_GPIO_EXT_PORTA_OFFSET));
  m.attr("RK3399_GRF_GPIO2_3_4_P_OFFSET")=nb::cast((RK3399_GRF_GPIO2_3_4_P_OFFSET));
  m.attr("RK3399_PMUGRF_GPIO0_1_P_OFFSET")=nb::cast((RK3399_PMUGRF_GPIO0_1_P_OFFSET));
  m.attr("RK3399_PMUGRF_BASE")=nb::cast((RK3399_PMUGRF_BASE));
  m.attr("RK3399_GRF_BASE")=nb::cast((RK3399_GRF_BASE));
  m.attr("RK3399_CRU_BASE")=nb::cast((RK3399_CRU_BASE));
  m.attr("RK3399_PMUCRU_BASE")=nb::cast((RK3399_PMUCRU_BASE));
  m.attr("RK3399_CRU_CLKGATE_CON31_OFFSET")=nb::cast((RK3399_CRU_CLKGATE_CON31_OFFSET));
  m.attr("RK3399_PMUCRU_CLKGATE_CON1_OFFSET")=nb::cast((RK3399_PMUCRU_CLKGATE_CON1_OFFSET));
  m.attr("RK3328_GPIO2_BASE")=nb::cast((RK3328_GPIO2_BASE));
  m.attr("RK3328_GPIO3_BASE")=nb::cast((RK3328_GPIO3_BASE));
  m.attr("RK3328_GPIO_NUM")=nb::cast((RK3328_GPIO_NUM));
  m.attr("RK3328_GPIO_SWPORTA_DR_OFFSET")=nb::cast((RK3328_GPIO_SWPORTA_DR_OFFSET));
  m.attr("RK3328_GPIO_SWPORTA_DDR_OFFSET")=nb::cast((RK3328_GPIO_SWPORTA_DDR_OFFSET));
  m.attr("RK3328_GPIO_EXT_PORTA_OFFSET")=nb::cast((RK3328_GPIO_EXT_PORTA_OFFSET));
  m.attr("RK3328_GRF_BASE")=nb::cast((RK3328_GRF_BASE));
  m.attr("RK3328_CRU_BASE")=nb::cast((RK3328_CRU_BASE));
  m.attr("RK3328_CRU_CLKGATE_CON16_OFFSET")=nb::cast((RK3328_CRU_CLKGATE_CON16_OFFSET));
  m.attr("S905_D3_GPIO_BASE")=nb::cast((S905D3_GPIO_BASE));
  m.attr("S905_D3_GPIO_AO_BASE")=nb::cast((S905D3_GPIO_AO_BASE));
  m.attr("S905_D3_GPIO_PWM_BASE")=nb::cast((S905D3_GPIO_PWM_BASE));
  m.attr("S905_D3_GPIO_PWM_AO_BASE")=nb::cast((S905D3_GPIO_PWM_AO_BASE));
  m.attr("S905_D3_GPIO_A_OUT_EN_REG")=nb::cast((S905D3_GPIOA_OUT_EN_REG));
  m.attr("S905_D3_GPIO_A_OUT_REG")=nb::cast((S905D3_GPIOA_OUT_REG));
  m.attr("S905_D3_GPIO_A_IN_REG")=nb::cast((S905D3_GPIOA_IN_REG));
  m.attr("S905_D3_GPIO_A_PUPD_REG")=nb::cast((S905D3_GPIOA_PUPD_REG));
  m.attr("S905_D3_GPIO_A_PUEN_REG")=nb::cast((S905D3_GPIOA_PUEN_REG));
  m.attr("S905_D3_GPIO_A_MUX_REG1")=nb::cast((S905D3_GPIOA_MUX_REG1));
  m.attr("S905_D3_GPIO_A_MUX_REG2")=nb::cast((S905D3_GPIOA_MUX_REG2));
  m.attr("S905_D3_GPIO_C_OUT_EN_REG")=nb::cast((S905D3_GPIOC_OUT_EN_REG));
  m.attr("S905_D3_GPIO_C_OUT_REG")=nb::cast((S905D3_GPIOC_OUT_REG));
  m.attr("S905_D3_GPIO_C_IN_REG")=nb::cast((S905D3_GPIOC_IN_REG));
  m.attr("S905_D3_GPIO_C_PUPD_REG")=nb::cast((S905D3_GPIOC_PUPD_REG));
  m.attr("S905_D3_GPIO_C_PUEN_REG")=nb::cast((S905D3_GPIOC_PUEN_REG));
  m.attr("S905_D3_GPIO_C_MUX_REG")=nb::cast((S905D3_GPIOC_MUX_REG));
  m.attr("S905_D3_GPIO_H_OUT_EN_REG")=nb::cast((S905D3_GPIOH_OUT_EN_REG));
  m.attr("S905_D3_GPIO_H_OUT_REG")=nb::cast((S905D3_GPIOH_OUT_REG));
  m.attr("S905_D3_GPIO_H_IN_REG")=nb::cast((S905D3_GPIOH_IN_REG));
  m.attr("S905_D3_GPIO_H_PUPD_REG")=nb::cast((S905D3_GPIOH_PUPD_REG));
  m.attr("S905_D3_GPIO_H_PUEN_REG")=nb::cast((S905D3_GPIOH_PUEN_REG));
  m.attr("S905_D3_GPIO_H_MUX_REG1")=nb::cast((S905D3_GPIOH_MUX_REG1));
  m.attr("S905_D3_GPIO_H_MUX_REG2")=nb::cast((S905D3_GPIOH_MUX_REG2));
  m.attr("S905_D3_GPIO_AO_OUT_EN_REG")=nb::cast((S905D3_GPIOAO_OUT_EN_REG));
  m.attr("S905_D3_GPIO_AO_OUT_REG")=nb::cast((S905D3_GPIOAO_OUT_REG));
  m.attr("S905_D3_GPIO_AO_IN_REG")=nb::cast((S905D3_GPIOAO_IN_REG));
  m.attr("S905_D3_GPIO_AO_PUPD_REG")=nb::cast((S905D3_GPIOAO_PUPD_REG));
  m.attr("S905_D3_GPIO_AO_PUEN_REG")=nb::cast((S905D3_GPIOAO_PUEN_REG));
  m.attr("S905_D3_GPIO_AO_MUX_REG1")=nb::cast((S905D3_GPIOAO_MUX_REG1));
  m.attr("S905_D3_GPIO_AO_MUX_REG2")=nb::cast((S905D3_GPIOAO_MUX_REG2));
  m.attr("S905_D3_PWM_DUTY_CYCLE_F_REG")=nb::cast((S905D3_PWM_DUTY_CYCLE_F_REG));
  m.attr("S905_D3_PWM_MISC_EF_REG")=nb::cast((S905D3_PWM_MISC_EF_REG));
  m.attr("S905_D3_PWM_DUTY_CYCLE_AO_C_REG")=nb::cast((S905D3_PWM_DUTY_CYCLE_AO_C_REG));
  m.attr("S905_D3_PWM_MISC_AO_CD_REG")=nb::cast((S905D3_PWM_MISC_AO_CD_REG));
  m.attr("S905_D3_PWM_CLK_EN_1")=nb::cast((S905D3_PWM_CLK_EN_1));
  m.attr("S905_D3_PWM_CLK_DIV_1")=nb::cast((S905D3_PWM_CLK_DIV_1));
  m.attr("S905_D3_PWM_CLK_EN_0")=nb::cast((S905D3_PWM_CLK_EN_0));
  m.attr("S905_D3_PWM_CLK_DIV_0")=nb::cast((S905D3_PWM_CLK_DIV_0));
  m.attr("S905_D3_PWM_CLK_SEL_1")=nb::cast((S905D3_PWM_CLK_SEL_1));
  m.attr("S905_D3_PWM_CLK_SEL_0")=nb::cast((S905D3_PWM_CLK_SEL_0));
  m.attr("S905_D3_PWM_EN_1")=nb::cast((S905D3_PWM_EN_1));
  m.attr("S905_D3_PWM_EN_0")=nb::cast((S905D3_PWM_EN_0));
  m.attr("A310_B_IOMUX_BASE_GROUP0")=nb::cast((A310B_IOMUX_BASE_GROUP0));
  m.attr("A310_B_IOMUX_BASE_GROUP1")=nb::cast((A310B_IOMUX_BASE_GROUP1));
  m.attr("A310_B_IOMUX_BASE_GROUP2")=nb::cast((A310B_IOMUX_BASE_GROUP2));
  m.attr("A310_B_IOMUX_BASE_GROUP3")=nb::cast((A310B_IOMUX_BASE_GROUP3));
  m.attr("A310_B_IOMUX_BASE_GROUP4")=nb::cast((A310B_IOMUX_BASE_GROUP4));
  m.attr("A310_B_IOMUX_BASE_GROUP5")=nb::cast((A310B_IOMUX_BASE_GROUP5));
  m.attr("A310_B_IOMUX_BASE_GROUP7")=nb::cast((A310B_IOMUX_BASE_GROUP7));
  m.attr("A310_B_GPIO_BASE_GROUP0")=nb::cast((A310B_GPIO_BASE_GROUP0));
  m.attr("A310_B_GPIO_BASE_GROUP1")=nb::cast((A310B_GPIO_BASE_GROUP1));
  m.attr("A310_B_GPIO_BASE_GROUP2")=nb::cast((A310B_GPIO_BASE_GROUP2));
  m.attr("A310_B_GPIO_BASE_GROUP3")=nb::cast((A310B_GPIO_BASE_GROUP3));
  m.attr("A310_B_GPIO_BASE_GROUP4")=nb::cast((A310B_GPIO_BASE_GROUP4));
  m.attr("A310_B_GPIO_BASE_GROUP5")=nb::cast((A310B_GPIO_BASE_GROUP5));
  m.attr("A310_B_GPIO_BASE_GROUP7")=nb::cast((A310B_GPIO_BASE_GROUP7));
  m.attr("A310_B_GPIO_DIRECTION_OFFSET")=nb::cast((A310B_GPIO_DIRECTION_OFFSET));
  m.attr("A310_B_GPIO_SET_VALUE_OFFSET")=nb::cast((A310B_GPIO_SET_VALUE_OFFSET));
  m.attr("A310_B_GPIO_GET_VALUE_OFFSET")=nb::cast((A310B_GPIO_GET_VALUE_OFFSET));
  m.attr("A310_B_PWM_BASE")=nb::cast((A310B_PWM_BASE));
  m.attr("A310_B_PWM_PRD2_OFFSET")=nb::cast((A310B_PWM_PRD2_OFFSET));
  m.attr("A310_B_PWM_CH2_PWL_OFFSET")=nb::cast((A310B_PWM_CH2_PWL_OFFSET));
  m.attr("A310_B_PWM_CH2_PWH_OFFSET")=nb::cast((A310B_PWM_CH2_PWH_OFFSET));
  m.attr("A310_B_PWM_PRD3_OFFSET")=nb::cast((A310B_PWM_PRD3_OFFSET));
  m.attr("A310_B_PWM_CH3_PWL_OFFSET")=nb::cast((A310B_PWM_CH3_PWL_OFFSET));
  m.attr("A310_B_PWM_CH3_PWH_OFFSET")=nb::cast((A310B_PWM_CH3_PWH_OFFSET));
  m.attr("A310_B_PWM_MEASURE_TIME_OFFSET")=nb::cast((A310B_PWM_MEASURE_TIME_OFFSET));
  m.attr("A310_P_IOMUX_BASE_GROUP0")=nb::cast((A310P_IOMUX_BASE_GROUP0));
  m.attr("A310_P_IOMUX_BASE_GROUP1")=nb::cast((A310P_IOMUX_BASE_GROUP1));
  m.attr("A310_P_IOMUX_BASE_GROUP2")=nb::cast((A310P_IOMUX_BASE_GROUP2));
  m.attr("A310_P_IOMUX_BASE_GROUP3")=nb::cast((A310P_IOMUX_BASE_GROUP3));
  m.attr("A310_P_IOMUX_BASE_GROUP4")=nb::cast((A310P_IOMUX_BASE_GROUP4));
  m.attr("A310_P_IOMUX_BASE_GROUP5")=nb::cast((A310P_IOMUX_BASE_GROUP5));
  m.attr("A310_P_GPIO_BASE_GROUP0")=nb::cast((A310P_GPIO_BASE_GROUP0));
  m.attr("A310_P_GPIO_BASE_GROUP1")=nb::cast((A310P_GPIO_BASE_GROUP1));
  m.attr("A310_P_GPIO_BASE_GROUP2")=nb::cast((A310P_GPIO_BASE_GROUP2));
  m.attr("A310_P_GPIO_BASE_GROUP3")=nb::cast((A310P_GPIO_BASE_GROUP3));
  m.attr("A310_P_GPIO_BASE_GROUP4")=nb::cast((A310P_GPIO_BASE_GROUP4));
  m.attr("A310_P_GPIO_BASE_GROUP5")=nb::cast((A310P_GPIO_BASE_GROUP5));
  m.attr("A310_P_GPIO_DIRECTION_OFFSET")=nb::cast((A310P_GPIO_DIRECTION_OFFSET));
  m.attr("A310_P_GPIO_SET_VALUE_OFFSET")=nb::cast((A310P_GPIO_SET_VALUE_OFFSET));
  m.attr("A310_P_GPIO_GET_VALUE_OFFSET")=nb::cast((A310P_GPIO_GET_VALUE_OFFSET));
  m.attr("A310_P_PWM_BASE")=nb::cast((A310P_PWM_BASE));
  m.attr("A310_P_PWM_PRD1_OFFSET")=nb::cast((A310P_PWM_PRD1_OFFSET));
  m.attr("A310_P_PWM_CH1_PWL_OFFSET")=nb::cast((A310P_PWM_CH1_PWL_OFFSET));
  m.attr("A310_P_PWM_CH1_PWH_OFFSET")=nb::cast((A310P_PWM_CH1_PWH_OFFSET));
  m.attr("A310_P_PWM_MEASURE_TIME_OFFSET")=nb::cast((A310P_PWM_MEASURE_TIME_OFFSET));
  m.attr("JH7110_SYS_IOMUX_BASE")=nb::cast((JH7110_SYS_IOMUX_BASE));
  m.attr("JH7110_SYS_DOEN_REG_BASE")=nb::cast((JH7110_SYS_DOEN_REG_BASE));
  m.attr("JH7110_SYS_DOUT_REG_BASE")=nb::cast((JH7110_SYS_DOUT_REG_BASE));
  m.attr("JH7110_SYS_GPI_REG_BASE")=nb::cast((JH7110_SYS_GPI_REG_BASE));
  m.attr("JH7110_SYS_GPIO_IN_REG_BASE")=nb::cast((JH7110_SYS_GPIOIN_REG_BASE));
  m.attr("JH7110_DOEN_MASK")=nb::cast((JH7110_DOEN_MASK));
  m.attr("JH7110_DOUT_MASK")=nb::cast((JH7110_DOUT_MASK));
  m.attr("JH7110_SYS_GPO_PDA_0_74_CFG")=nb::cast((JH7110_SYS_GPO_PDA_0_74_CFG));
  m.attr("JH7110_GPOEN_ENABLE")=nb::cast((JH7110_GPOEN_ENABLE));
  m.attr("JH7110_GPOEN_DISABLE")=nb::cast((JH7110_GPOEN_DISABLE));
  m.attr("GPIO_NUM_PER_WORD")=nb::cast((GPIO_NUM_PER_WORD));
  m.attr("KYX1_GPIO_BASE")=nb::cast((KYX1_GPIO_BASE));
  m.attr("KYX1_IOMUX_BASE")=nb::cast((KYX1_IOMUX_BASE));
  m.attr("KYX1_FUNC_MASK")=nb::cast((KYX1_FUNC_MASK));
  m.attr("KYX1_OFFSET")=nb::cast((KYX1_OFFSET));
  m.attr("KYX1_PULL_DIS")=nb::cast((KYX1_PULL_DIS));
  m.attr("KYX1_PULL_UP")=nb::cast((KYX1_PULL_UP));
  m.attr("KYX1_PULL_DOWN")=nb::cast((KYX1_PULL_DOWN));
  m.attr("PI_GPIO_MASK")=nb::cast((PI_GPIO_MASK));
  m.attr("WPI_MODE_PINS")=nb::cast((WPI_MODE_PINS));
  m.attr("WPI_MODE_GPIO")=nb::cast((WPI_MODE_GPIO));
  m.attr("WPI_MODE_GPIO_SYS")=nb::cast((WPI_MODE_GPIO_SYS));
  m.attr("WPI_MODE_PHYS")=nb::cast((WPI_MODE_PHYS));
  m.attr("WPI_MODE_PIFACE")=nb::cast((WPI_MODE_PIFACE));
  m.attr("WPI_MODE_UNINITIALISED")=nb::cast((WPI_MODE_UNINITIALISED));
  m.attr("INPUT")=nb::cast((INPUT));
  m.attr("OUTPUT")=nb::cast((OUTPUT));
  m.attr("PWM_OUTPUT")=nb::cast((PWM_OUTPUT));
  m.attr("GPIO_CLOCK")=nb::cast((GPIO_CLOCK));
  m.attr("SOFT_PWM_OUTPUT")=nb::cast((SOFT_PWM_OUTPUT));
  m.attr("SOFT_TONE_OUTPUT")=nb::cast((SOFT_TONE_OUTPUT));
  m.attr("PWM_TONE_OUTPUT")=nb::cast((PWM_TONE_OUTPUT));
  m.attr("LOW")=nb::cast((LOW));
  m.attr("HIGH")=nb::cast((HIGH));
  m.attr("PUD_OFF")=nb::cast((PUD_OFF));
  m.attr("PUD_DOWN")=nb::cast((PUD_DOWN));
  m.attr("PUD_UP")=nb::cast((PUD_UP));
  m.attr("PWM_MODE_MS")=nb::cast((PWM_MODE_MS));
  m.attr("PWM_MODE_BAL")=nb::cast((PWM_MODE_BAL));
  m.attr("INT_EDGE_SETUP")=nb::cast((INT_EDGE_SETUP));
  m.attr("INT_EDGE_FALLING")=nb::cast((INT_EDGE_FALLING));
  m.attr("INT_EDGE_RISING")=nb::cast((INT_EDGE_RISING));
  m.attr("INT_EDGE_BOTH")=nb::cast((INT_EDGE_BOTH));
  m.attr("PI_MODEL_3")=nb::cast((PI_MODEL_3));
  m.attr("PI_MODEL_LTIE_2")=nb::cast((PI_MODEL_LTIE_2));
  m.attr("PI_MODEL_ZERO")=nb::cast((PI_MODEL_ZERO));
  m.attr("PI_MODEL_H3")=nb::cast((PI_MODEL_H3));
  m.attr("PI_MODEL_ZERO_PLUS_2")=nb::cast((PI_MODEL_ZERO_PLUS_2));
  m.attr("PI_MODEL_WIN")=nb::cast((PI_MODEL_WIN));
  m.attr("PI_MODEL_PRIME")=nb::cast((PI_MODEL_PRIME));
  m.attr("PI_MODEL_PC_2")=nb::cast((PI_MODEL_PC_2));
  m.attr("PI_MODEL_ZERO_PLUS")=nb::cast((PI_MODEL_ZERO_PLUS));
  m.attr("PI_MODEL_ZERO_2")=nb::cast((PI_MODEL_ZERO_2));
  m.attr("PI_MODEL_ZERO_2_W")=nb::cast((PI_MODEL_ZERO_2_W));
  m.attr("PI_MODEL_ZERO_3_PLUS")=nb::cast((PI_MODEL_ZERO_3_PLUS));
  m.attr("PI_MODEL_800")=nb::cast((PI_MODEL_800));
  m.attr("PI_MODEL_4")=nb::cast((PI_MODEL_4));
  m.attr("PI_MODEL_4_LTS")=nb::cast((PI_MODEL_4_LTS));
  m.attr("PI_MODEL_RK3399")=nb::cast((PI_MODEL_RK3399));
  m.attr("PI_MODEL_R1_PLUS")=nb::cast((PI_MODEL_R1_PLUS));
  m.attr("PI_MODEL_900")=nb::cast((PI_MODEL_900));
  m.attr("PI_MODEL_5")=nb::cast((PI_MODEL_5));
  m.attr("PI_MODEL_5_B")=nb::cast((PI_MODEL_5B));
  m.attr("PI_MODEL_5_PRO")=nb::cast((PI_MODEL_5_PRO));
  m.attr("PI_MODEL_5_MAX")=nb::cast((PI_MODEL_5_MAX));
  m.attr("PI_MODEL_5_PLUS")=nb::cast((PI_MODEL_5_PLUS));
  m.attr("PI_MODEL_CM5")=nb::cast((PI_MODEL_CM5));
  m.attr("PI_MODEL_CM5_TABLET")=nb::cast((PI_MODEL_CM5_TABLET));
  m.attr("PI_MODEL_5_ULTRA")=nb::cast((PI_MODEL_5_ULTRA));
  m.attr("PI_MODEL_AI_MAX")=nb::cast((PI_MODEL_AI_MAX));
  m.attr("PI_MODEL_CM4")=nb::cast((PI_MODEL_CM4));
  m.attr("PI_MODEL_3_B")=nb::cast((PI_MODEL_3B));
  m.attr("PI_MODEL_3_PLUS")=nb::cast((PI_MODEL_3_PLUS));
  m.attr("PI_MODEL_AI_PRO")=nb::cast((PI_MODEL_AI_PRO));
  m.attr("PI_MODEL_KUNPENG_PRO")=nb::cast((PI_MODEL_KUNPENG_PRO));
  m.attr("PI_MODEL_AI_STATION")=nb::cast((PI_MODEL_AI_STATION));
  m.attr("PI_MODEL_RV")=nb::cast((PI_MODEL_RV));
  m.attr("PI_MODEL_4_A")=nb::cast((PI_MODEL_4A));
  m.attr("PI_MODEL_RV2")=nb::cast((PI_MODEL_RV2));
  m.attr("PI_MODEL_4_PRO")=nb::cast((PI_MODEL_4_PRO));
  m.attr("PI_MODEL_ZERO_3_W")=nb::cast((PI_MODEL_ZERO_3_W));
  m.attr("PI_MODEL_ZERO_4")=nb::cast((PI_MODEL_ZERO_4));
  m.attr("WPI_FATAL")=nb::cast((WPI_FATAL));
  m.attr("WPI_ALMOST")=nb::cast((WPI_ALMOST));
}
