"""nanobind bindings for wiringPi/font.h"""



class FontInfo:
    def __init__(self) -> None: ...

    @property
    def width(self) -> int: ...

    @width.setter
    def width(self, arg: int, /) -> None: ...

    @property
    def height(self) -> int: ...

    @height.setter
    def height(self, arg: int, /) -> None: ...

    @property
    def spacing(self) -> int: ...

    @spacing.setter
    def spacing(self, arg: int, /) -> None: ...

    @property
    def offset(self) -> int: ...

    @offset.setter
    def offset(self, arg: int, /) -> None: ...

    @property
    def data_address(self) -> int: ...

    @data_address.setter
    def data_address(self, arg: int, /) -> None: ...

font1_data: bytes = ...

font2_data: bytes = ...

font3_data: bytes = ...

def get_font1() -> FontInfo: ...

def set_font1(value: FontInfo) -> None: ...

def get_font2() -> FontInfo: ...

def set_font2(value: FontInfo) -> None: ...

def get_font3() -> FontInfo: ...

def set_font3(value: FontInfo) -> None: ...
