"""nanobind bindings for wiringPi/w25q64.h"""



def w25q64_begin(cs: int) -> None: ...

def w25q64_read_status_reg1() -> int: ...

def w25q64_read_status_reg2() -> int: ...

def w25q64_read_manufacturer() -> bytes: ...

def w25q64_read_unique_id() -> bytes: ...

def w25q64_is_busy() -> bool: ...

def w25q64_power_down() -> None: ...

def w25q64_write_enable() -> None: ...

def w25q64_write_disable() -> None: ...

def w25q64_read(addr: int, n: int) -> bytes: ...

def w25q64_fast_read(addr: int, n: int) -> bytes: ...

def w25q64_erase_sector(sect_no: int, flgwait: bool) -> bool: ...

def w25q64_erase64_block(blk_no: int, flgwait: bool) -> bool: ...

def w25q64_erase32_block(blk_no: int, flgwait: bool) -> bool: ...

def w25q64_erase_all(flgwait: bool) -> bool: ...

def w25q64_page_write(sect_no: int, inaddr: int, data: object) -> int: ...
