"""nanobind bindings for wiringPi/wiringPiSPI.h"""



def wiring_pi_spi_get_fd(channel: int) -> int: ...

def wiring_pi_spi_data_rw(channel: int, data: object) -> int: ...

def wiring_pi_spi_setup_mode(channel: int, port: int, speed: int, mode: int) -> int: ...

def wiring_pi_spi_setup(channel: int, speed: int) -> int: ...
