"""nanobind bindings for wiringPi/wiringSerial.h"""

from collections.abc import Sequence
from typing import overload


class SerialConfig:
    def __init__(self) -> None: ...

    @property
    def struct_size(self) -> int: ...

    @struct_size.setter
    def struct_size(self, arg: int, /) -> None: ...

    @property
    def version(self) -> int: ...

    @version.setter
    def version(self, arg: int, /) -> None: ...

    @property
    def baud(self) -> int: ...

    @baud.setter
    def baud(self, arg: int, /) -> None: ...

    @property
    def data_bits(self) -> int: ...

    @data_bits.setter
    def data_bits(self, arg: int, /) -> None: ...

    @property
    def parity(self) -> int: ...

    @parity.setter
    def parity(self, arg: int, /) -> None: ...

    @property
    def stop_bits(self) -> int: ...

    @stop_bits.setter
    def stop_bits(self, arg: int, /) -> None: ...

    @property
    def flow_control(self) -> int: ...

    @flow_control.setter
    def flow_control(self, arg: int, /) -> None: ...

    @property
    def xon_char(self) -> int: ...

    @xon_char.setter
    def xon_char(self, arg: int, /) -> None: ...

    @property
    def xoff_char(self) -> int: ...

    @xoff_char.setter
    def xoff_char(self, arg: int, /) -> None: ...

    @property
    def vmin(self) -> int: ...

    @vmin.setter
    def vmin(self, arg: int, /) -> None: ...

    @property
    def vtime(self) -> int: ...

    @vtime.setter
    def vtime(self, arg: int, /) -> None: ...

    @property
    def reserved(self) -> tuple: ...

    @reserved.setter
    def reserved(self, arg: Sequence, /) -> None: ...

class SerialRS485Config:
    def __init__(self) -> None: ...

    @property
    def struct_size(self) -> int: ...

    @struct_size.setter
    def struct_size(self, arg: int, /) -> None: ...

    @property
    def flags(self) -> int: ...

    @flags.setter
    def flags(self, arg: int, /) -> None: ...

    @property
    def delay_before_send_ms(self) -> int: ...

    @delay_before_send_ms.setter
    def delay_before_send_ms(self, arg: int, /) -> None: ...

    @property
    def delay_after_send_ms(self) -> int: ...

    @delay_after_send_ms.setter
    def delay_after_send_ms(self, arg: int, /) -> None: ...

    @property
    def receive_address(self) -> int: ...

    @receive_address.setter
    def receive_address(self, arg: int, /) -> None: ...

    @property
    def destination_address(self) -> int: ...

    @destination_address.setter
    def destination_address(self, arg: int, /) -> None: ...

    @property
    def reserved8(self) -> bytes: ...

    @reserved8.setter
    def reserved8(self, arg: bytes, /) -> None: ...

    @property
    def reserved(self) -> tuple: ...

    @reserved.setter
    def reserved(self, arg: Sequence, /) -> None: ...

class SerialCounters:
    def __init__(self) -> None: ...

    @property
    def struct_size(self) -> int: ...

    @struct_size.setter
    def struct_size(self, arg: int, /) -> None: ...

    @property
    def cts(self) -> int: ...

    @cts.setter
    def cts(self, arg: int, /) -> None: ...

    @property
    def dsr(self) -> int: ...

    @dsr.setter
    def dsr(self, arg: int, /) -> None: ...

    @property
    def rng(self) -> int: ...

    @rng.setter
    def rng(self, arg: int, /) -> None: ...

    @property
    def dcd(self) -> int: ...

    @dcd.setter
    def dcd(self, arg: int, /) -> None: ...

    @property
    def rx(self) -> int: ...

    @rx.setter
    def rx(self, arg: int, /) -> None: ...

    @property
    def tx(self) -> int: ...

    @tx.setter
    def tx(self, arg: int, /) -> None: ...

    @property
    def frame(self) -> int: ...

    @frame.setter
    def frame(self, arg: int, /) -> None: ...

    @property
    def overrun(self) -> int: ...

    @overrun.setter
    def overrun(self, arg: int, /) -> None: ...

    @property
    def parity(self) -> int: ...

    @parity.setter
    def parity(self, arg: int, /) -> None: ...

    @property
    def brk(self) -> int: ...

    @brk.setter
    def brk(self, arg: int, /) -> None: ...

    @property
    def buf_overrun(self) -> int: ...

    @buf_overrun.setter
    def buf_overrun(self, arg: int, /) -> None: ...

    @property
    def reserved(self) -> tuple: ...

    @reserved.setter
    def reserved(self, arg: Sequence, /) -> None: ...

class SerialHardwareInfo:
    def __init__(self) -> None: ...

    @property
    def struct_size(self) -> int: ...

    @struct_size.setter
    def struct_size(self, arg: int, /) -> None: ...

    @property
    def hardware_type(self) -> int: ...

    @hardware_type.setter
    def hardware_type(self, arg: int, /) -> None: ...

    @property
    def fifo_size(self) -> int: ...

    @fifo_size.setter
    def fifo_size(self, arg: int, /) -> None: ...

    @property
    def baud_base(self) -> int: ...

    @baud_base.setter
    def baud_base(self, arg: int, /) -> None: ...

    @property
    def port_type(self) -> int: ...

    @port_type.setter
    def port_type(self, arg: int, /) -> None: ...

    @property
    def line(self) -> int: ...

    @line.setter
    def line(self, arg: int, /) -> None: ...

    @property
    def capabilities(self) -> int: ...

    @capabilities.setter
    def capabilities(self, arg: int, /) -> None: ...

    @property
    def reserved(self) -> tuple: ...

    @reserved.setter
    def reserved(self, arg: Sequence, /) -> None: ...

def serial_open(device: str, baud: int) -> int: ...

def serial_close(fd: int) -> None: ...

def serial_flush(fd: int) -> None: ...

def serial_putchar(fd: int, c: int) -> None: ...

def serial_puts(fd: int, s: str) -> None: ...

def serial_printf(fd: int, message: str) -> None: ...

def serial_data_avail(fd: int) -> int: ...

def serial_getchar(fd: int) -> int: ...

def serial_config_init() -> SerialConfig: ...

def serial_open_config(device: str, config: SerialConfig) -> int: ...

def serial_get_config(fd: int) -> tuple: ...

def serial_set_config(fd: int, config: SerialConfig) -> int: ...

def serial_get_baud(fd: int) -> tuple: ...

def serial_set_baud(fd: int, baud: int) -> int: ...

def serial_read(fd: int, count: int) -> bytes: ...

def serial_write(fd: int, data: object) -> int: ...

def serial_read_timeout(fd: int, count: int, timeout_ms: int, inter_byte_timeout_ms: int = -1) -> bytes: ...

def serial_write_timeout(fd: int, data: object, timeout_ms: int) -> int: ...

def serial_drain(fd: int) -> int: ...

def serial_flush_input(fd: int) -> int: ...

def serial_flush_output(fd: int) -> int: ...

def serial_input_waiting(fd: int) -> int: ...

def serial_output_waiting(fd: int) -> int: ...

def serial_send_break(fd: int, duration_ms: int) -> int: ...

def serial_set_break(fd: int, enabled: int) -> int: ...

def serial_get_modem_lines(fd: int) -> tuple: ...

def serial_set_modem_lines(fd: int, set_mask: int, clear_mask: int) -> int: ...

def serial_set_rts(fd: int, enabled: int) -> int: ...

def serial_set_dtr(fd: int, enabled: int) -> int: ...

def serial_get_cts(fd: int) -> int: ...

def serial_get_dsr(fd: int) -> int: ...

def serial_get_ri(fd: int) -> int: ...

def serial_get_cd(fd: int) -> int: ...

def serial_set_input_flow(fd: int, enabled: int) -> int: ...

def serial_set_output_flow(fd: int, enabled: int) -> int: ...

def serial_set_exclusive(fd: int, enabled: int) -> int: ...

def serial_get_low_latency(fd: int) -> int: ...

def serial_set_low_latency(fd: int, enabled: int) -> int: ...

def serial_get_counters(fd: int) -> tuple: ...

def serial_tx_empty(fd: int) -> int: ...

def serial_get_rs485(fd: int) -> tuple: ...

def serial_set_rs485(fd: int, config: SerialRS485Config) -> int: ...

def serial_get_rx_trigger(fd: int) -> int: ...

def serial_set_rx_trigger(fd: int, bytes: int) -> int: ...

def serial_get_wakeup(fd: int) -> int: ...

def serial_set_wakeup(fd: int, enabled: int) -> int: ...

def serial_get_hardware_info(fd: int) -> tuple: ...

def serial_get_capabilities(fd: int) -> tuple: ...

def serial_context_open(device: str, config: SerialConfig) -> int: ...

def serial_context_from_fd(fd: int, take_ownership: int = 0) -> int: ...

def serial_context_close(address: int) -> None: ...

def serial_context_get_fd(address: int) -> int: ...

def serial_context_read(address: int, count: int, timeout_ms: int = -1, inter_byte_timeout_ms: int = -1) -> bytes: ...

def serial_context_write(address: int, data: object, timeout_ms: int = -1) -> int: ...

def serial_context_cancel_read(address: int) -> int: ...

def serial_context_cancel_write(address: int) -> int: ...

SERIAL_CONFIG_VERSION: int = 1

SERIAL_CONFIG_STRUCT_SIZE: int = 36

SERIAL_PARITY_NONE: int = 0

SERIAL_PARITY_ODD: int = 1

SERIAL_PARITY_EVEN: int = 2

SERIAL_PARITY_MARK: int = 3

SERIAL_PARITY_SPACE: int = 4

SERIAL_STOP_BITS_ONE: int = 1

SERIAL_STOP_BITS_ONE_POINT_FIVE: int = 2

SERIAL_STOP_BITS_TWO: int = 3

SERIAL_FLOW_NONE: int = 0

SERIAL_FLOW_XON_XOFF: int = 1

SERIAL_FLOW_RTS_CTS: int = 2

SERIAL_MODEM_RTS: int = 1

SERIAL_MODEM_DTR: int = 2

SERIAL_MODEM_CTS: int = 4

SERIAL_MODEM_DSR: int = 8

SERIAL_MODEM_RI: int = 16

SERIAL_MODEM_CD: int = 32

SERIAL_MODEM_LOOP: int = 64

SERIAL_RS485_ENABLED: int = 1

SERIAL_RS485_RTS_ON_SEND: int = 2

SERIAL_RS485_RTS_AFTER_SEND: int = 4

SERIAL_RS485_RX_DURING_TX: int = 8

SERIAL_RS485_TERMINATE_BUS: int = 16

SERIAL_RS485_ADDRESS_MODE: int = 32

SERIAL_RS485_RX_ADDRESS: int = 64

SERIAL_RS485_DEST_ADDRESS: int = 128

SERIAL_RS485_MODE_RS422: int = 256

SERIAL_CAP_CUSTOM_BAUD: int = 1

SERIAL_CAP_MARK_SPACE_PARITY: int = 2

SERIAL_CAP_XON_XOFF: int = 4

SERIAL_CAP_RTS_CTS: int = 8

SERIAL_CAP_MODEM_CONTROL: int = 16

SERIAL_CAP_MODEM_STATUS: int = 32

SERIAL_CAP_EXCLUSIVE: int = 64

SERIAL_CAP_LOW_LATENCY: int = 128

SERIAL_CAP_RS485: int = 256

SERIAL_CAP_ICOUNT: int = 512

SERIAL_CAP_TX_EMPTY: int = 1024

SERIAL_CAP_RX_TRIGGER: int = 2048

SERIAL_CAP_WAKEUP: int = 4096

SERIAL_CAP_8250: int = 8192

SERIAL_CAP_DW_APB_UART: int = 16384

SERIAL_CAP_RK3588_UART: int = 32768

SERIAL_CAP_DMA_DESCRIBED: int = 65536

SERIAL_CAP_AUTO_RTS_CTS: int = 131072

SERIAL_CAP_FIFO: int = 262144

SERIAL_CAP_CANCEL_IO: int = 524288

SERIAL_HARDWARE_UNKNOWN: int = 0

SERIAL_HARDWARE_8250: int = 1

SERIAL_HARDWARE_DW_APB_UART: int = 2

SERIAL_HARDWARE_RK3588_UART: int = 3

class SerialPort:
    @overload
    def __init__(self, port: str, baudrate: int = 115200) -> None: ...

    @overload
    def __init__(self, port: str, config: SerialConfig) -> None: ...

    def open(self) -> None: ...

    def close(self) -> None: ...

    @property
    def is_open(self) -> bool: ...

    def fileno(self) -> int: ...

    @property
    def port(self) -> str: ...

    @property
    def name(self) -> str: ...

    @property
    def config(self) -> SerialConfig: ...

    @config.setter
    def config(self, arg: SerialConfig, /) -> None: ...

    @property
    def baudrate(self) -> int: ...

    @baudrate.setter
    def baudrate(self, arg: int, /) -> None: ...

    @property
    def baud(self) -> int: ...

    @baud.setter
    def baud(self, arg: int, /) -> None: ...

    @property
    def bytesize(self) -> int: ...

    @bytesize.setter
    def bytesize(self, arg: int, /) -> None: ...

    @property
    def parity(self) -> str: ...

    @parity.setter
    def parity(self, arg: str, /) -> None: ...

    @property
    def stopbits(self) -> float: ...

    @stopbits.setter
    def stopbits(self, arg: float, /) -> None: ...

    @property
    def xonxoff(self) -> bool: ...

    @xonxoff.setter
    def xonxoff(self, arg: bool, /) -> None: ...

    @property
    def rtscts(self) -> bool: ...

    @rtscts.setter
    def rtscts(self, arg: bool, /) -> None: ...

    @property
    def dsrdtr(self) -> bool: ...

    @dsrdtr.setter
    def dsrdtr(self, arg: bool, /) -> None: ...

    @property
    def timeout(self) -> object: ...

    @timeout.setter
    def timeout(self, value: object | None) -> None: ...

    @property
    def write_timeout(self) -> object: ...

    @write_timeout.setter
    def write_timeout(self, value: object | None) -> None: ...

    @property
    def inter_byte_timeout(self) -> object: ...

    @inter_byte_timeout.setter
    def inter_byte_timeout(self, value: object | None) -> None: ...

    @property
    def read_timeout_ms(self) -> int: ...

    @read_timeout_ms.setter
    def read_timeout_ms(self, arg: int, /) -> None: ...

    @property
    def write_timeout_ms(self) -> int: ...

    @write_timeout_ms.setter
    def write_timeout_ms(self, arg: int, /) -> None: ...

    @property
    def inter_byte_timeout_ms(self) -> int: ...

    @inter_byte_timeout_ms.setter
    def inter_byte_timeout_ms(self, arg: int, /) -> None: ...

    def read(self, size: int = 1) -> bytes: ...

    def read_into(self, buffer: object) -> int: ...

    def readinto(self, buffer: object) -> int: ...

    def write(self, data: object) -> int: ...

    def read_all(self) -> bytes: ...

    def read_until(self, expected: bytes = ..., size: int = 0) -> bytes: ...

    def flush(self) -> None: ...

    def drain(self) -> None: ...

    def reset_input_buffer(self) -> None: ...

    def reset_output_buffer(self) -> None: ...

    @property
    def in_waiting(self) -> int: ...

    @property
    def out_waiting(self) -> int: ...

    def send_break(self, duration: float = 0.25) -> None: ...

    @property
    def break_condition(self) -> bool: ...

    @break_condition.setter
    def break_condition(self, arg: bool, /) -> None: ...

    @property
    def rts(self) -> bool: ...

    @rts.setter
    def rts(self, arg: bool, /) -> None: ...

    @property
    def dtr(self) -> bool: ...

    @dtr.setter
    def dtr(self, arg: bool, /) -> None: ...

    @property
    def cts(self) -> bool: ...

    @property
    def dsr(self) -> bool: ...

    @property
    def ri(self) -> bool: ...

    @property
    def cd(self) -> bool: ...

    def set_input_flow_control(self, enable: bool) -> None: ...

    def set_output_flow_control(self, enable: bool) -> None: ...

    @property
    def exclusive(self) -> bool: ...

    @exclusive.setter
    def exclusive(self, arg: bool, /) -> None: ...

    @property
    def low_latency(self) -> bool: ...

    @low_latency.setter
    def low_latency(self, arg: bool, /) -> None: ...

    @property
    def counters(self) -> SerialCounters: ...

    @property
    def tx_empty(self) -> bool: ...

    @property
    def rs485_mode(self) -> SerialRS485Config: ...

    @rs485_mode.setter
    def rs485_mode(self, arg: SerialRS485Config, /) -> None: ...

    @property
    def rs485(self) -> SerialRS485Config: ...

    @rs485.setter
    def rs485(self, arg: SerialRS485Config, /) -> None: ...

    @property
    def rx_trigger(self) -> int: ...

    @rx_trigger.setter
    def rx_trigger(self, arg: int, /) -> None: ...

    @property
    def wakeup(self) -> bool: ...

    @wakeup.setter
    def wakeup(self, arg: bool, /) -> None: ...

    @property
    def hardware_info(self) -> SerialHardwareInfo: ...

    @property
    def capabilities(self) -> int: ...

    def cancel_read(self) -> None: ...

    def cancel_write(self) -> None: ...
