"""nanobind bindings for wiringPi/wiringPiI2C.h"""



def wiring_pi_i2c_read(fd: int) -> int: ...

def wiring_pi_i2c_read_reg8(fd: int, reg: int) -> int: ...

def wiring_pi_i2c_read_reg16(fd: int, reg: int) -> int: ...

def wiring_pi_i2c_write(fd: int, data: int) -> int: ...

def wiring_pi_i2c_write_reg8(fd: int, reg: int, data: int) -> int: ...

def wiring_pi_i2c_write_reg16(fd: int, reg: int, data: int) -> int: ...

def wiring_pi_i2c_setup_interface(device: str, dev_id: int) -> int: ...

def wiring_pi_i2c_setup(dev_id: int) -> int: ...
