"""nanobind bindings for wiringPiD/network.h"""



def get_client_ip() -> str: ...

def get_response_legacy(client_fd: int) -> int: ...

def setup_server(server_port: int) -> int: ...

def send_greeting(client_fd: int) -> int: ...

def send_challenge(client_fd: int) -> int: ...

def get_response(client_fd: int) -> int: ...

def password_match(password: str) -> int: ...

def close_server(client_fd: int) -> None: ...
