"""nanobind bindings for devLib/ds1302.h"""

from collections.abc import Sequence


def ds1302rtc_read(reg: int) -> int: ...

def ds1302rtc_write(reg: int, data: int) -> None: ...

def ds1302ram_read(addr: int) -> int: ...

def ds1302ram_write(addr: int, data: int) -> None: ...

def ds1302_clock_read() -> tuple: ...

def ds1302_clock_write(clock_data: Sequence) -> None: ...

def ds1302trickle_charge(diodes: int, resistors: int) -> None: ...

def ds1302setup(clock_pin: int, data_pin: int, cs_pin: int) -> None: ...
