"""nanobind bindings for devLib/gertboard.h"""



def gertboard_analog_write(chan: int, value: int) -> None: ...

def gertboard_analog_read(chan: int) -> int: ...

def gertboard_spi_setup() -> int: ...

def gertboard_analog_setup(pin_base: int) -> int: ...
