"""nanobind bindings for devLib/lcd.h"""



def lcd_home(fd: int) -> None: ...

def lcd_clear(fd: int) -> None: ...

def lcd_display(fd: int, state: int) -> None: ...

def lcd_cursor(fd: int, state: int) -> None: ...

def lcd_cursor_blink(fd: int, state: int) -> None: ...

def lcd_send_command(fd: int, command: int) -> None: ...

def lcd_position(fd: int, x: int, y: int) -> None: ...

def lcd_char_def(fd: int, index: int, data: bytes) -> None: ...

def lcd_putchar(fd: int, data: int) -> None: ...

def lcd_puts(fd: int, string: str) -> None: ...

def lcd_printf(fd: int, message: str) -> None: ...

def lcd_init(rows: int, cols: int, bits: int, rs: int, strb: int, d0: int, d1: int, d2: int, d3: int, d4: int, d5: int, d6: int, d7: int) -> int: ...

MAX_LCDS: int = 8
