"""nanobind bindings for devLib/lcd128x64.h"""



def lcd128x64set_origin(x: int, y: int) -> None: ...

def lcd128x64set_orientation(orientation: int) -> None: ...

def lcd128x64orient_coordinates() -> tuple: ...

def lcd128x64_get_screen_size() -> tuple: ...

def lcd128x64point(x: int, y: int, colour: int) -> None: ...

def lcd128x64line(x0: int, y0: int, x1: int, y1: int, colour: int) -> None: ...

def lcd128x64line_to(x: int, y: int, colour: int) -> None: ...

def lcd128x64rectangle(x1: int, y1: int, x2: int, y2: int, colour: int, filled: int) -> None: ...

def lcd128x64circle(x: int, y: int, r: int, colour: int, filled: int) -> None: ...

def lcd128x64ellipse(cx: int, cy: int, x_radius: int, y_radius: int, colour: int, filled: int) -> None: ...

def lcd128x64putchar(x: int, y: int, c: int, bg_col: int, fg_col: int) -> None: ...

def lcd128x64puts(x: int, y: int, str: str, bg_col: int, fg_col: int) -> None: ...

def lcd128x64update() -> None: ...

def lcd128x64clear(colour: int) -> None: ...

def lcd128x64setup() -> int: ...
