"""nanobind bindings for devLib/scrollPhat.h"""



def scroll_phat_point(x: int, y: int, colour: int) -> None: ...

def scroll_phat_line(x0: int, y0: int, x1: int, y1: int, colour: int) -> None: ...

def scroll_phat_line_to(x: int, y: int, colour: int) -> None: ...

def scroll_phat_rectangle(x1: int, y1: int, x2: int, y2: int, colour: int, filled: int) -> None: ...

def scroll_phat_update() -> None: ...

def scroll_phat_clear() -> None: ...

def scroll_phat_putchar(c: int) -> int: ...

def scroll_phat_puts(str: str) -> None: ...

def scroll_phat_printf(message: str) -> None: ...

def scroll_phat_print_speed(cps10: int) -> None: ...

def scroll_phat_intensity(percent: int) -> None: ...

def scroll_phat_setup() -> int: ...
